### ISSUE TITLE
sendMessage: E906

### ISSUE THREAD

**Issue by Shane-XB-Qian** [yegappan/lsp#11]
```vim
  var ch = lspserver.job->job_getchannel()
  ch->ch_sendraw(msg)
```
of `s:sendMessage`, looks not right, `ch` maybe not open, closed or buffered, then 'E906', cannot send.

// this happened when trying with ts lsp server.

**Comment by yegappan** [comment]
We could check the status of the channel before sending the message. But the job exit callback (exit_cb)
is supposed to be called when the LSP server exits. This function sets the LSP server job handle to v:none
and updates the LSP server running status to false. So further messages to this LSP server should not
be sent.

Did the LSP server exit because of an exception or error?

**Comment by Shane-XB-Qian** [comment]
yes, checked,
exit_cb was called, the code is `1`.
and that time, ch is 'buffered'.

**Comment by yegappan** [comment]
Committed #4c57eb5bdab1e1e0e3ff6bc2faec7e201e3ae08d to check for the status of the channel before sending the message to the LSP server.

**Comment by Shane-XB-Qian** [comment]
yea, that ch_status chk can avoid err raised.
// however not sure why ts lsp server cannot startup (exit '1'), or started, but failed later.
// so far just found ts lsp server is failed, maybe there was something special......................

**Comment by Shane-XB-Qian** [comment]
i did a rough debug, looks that was a lsp server code flaw: https://github.com/theia-ide/typescript-language-server/issues/191
// at least from the version at npm, looks...  FYI.

**Comment by yegappan** [comment]
Thanks for following up on this. Hopefully the typescript language server will handle this exception properly without exiting.

**Comment by Shane-XB-Qian** [comment]
for reference: above issue in ts lsp server had been fixed.
however another similar issue on perl lsp server still no clue.
// https://github.com/richterger/Perl-LanguageServer/issues/81
