### ISSUE TITLE
[Mark] didChangeConfiguration

### ISSUE THREAD

**Issue by Shane-XB-Qian** [yegappan/lsp#12]
looks haveNot impl method: ‘workspace/didChangeConfiguration’ yet
supposed you knew, but for a mark, so opening this ticket...

**Comment by yegappan** [comment]
Yes. The 'workspace/didChangeConfiguration' notification is not yet implemented. But from the LSP protocol
specification it is not clear to me when the client is supposed to send this notification to the LSP server and
how the LSP server will use this notification.

**Comment by Shane-XB-Qian** [comment]
actually, i am not sure, but i saw some lsp server would say what it supported cfg is, i am not sure if it was uniformed.
