### ISSUE TITLE
packadd lsp shows errors : (Error detected while processing BufRead Autocommands for "*": E121: Undefined variable: lsp)

### ISSUE THREAD

**Issue by mowazzem** [yegappan/lsp#122]

**Comment by hardselius** [comment]
#119 causes the problem. It should be either reverted or fixed.

**Comment by hardselius** [comment]
See comment: https://github.com/yegappan/lsp/pull/119#issuecomment-1348757091

**Comment by yegappan** [comment]
Can you create a PR to either revert this change or to fix it? I will merge it.
