### ISSUE TITLE
How to enable vsnip snippets?

### ISSUE THREAD

**Issue by maximyurevich** [yegappan/lsp#124]
Do I need to use another autocomplete plugin instead of the default one?
Shoud I add something like

```vim
let lspOpts = {'autoHighlightDiags': v:true, 'snippetSupport': v:true}
```
I can't trigger friendly snippets

**Comment by hydrasho** [comment]
same problem...

**Comment by girishji** [comment]
I think you need to map keys as stated in https://github.com/hrsh7th/vim-vsnip

These snippets did not show up in completion menu but I could invoke them through keymap.

You need also https://github.com/hrsh7th/vim-vsnip-integ

I don't see this plugin managing the completion list from vim-vsnip. That part is managed by above plugin. I am surprised why the interface is not straightforward and standardized, like functions we supply to `omnifunc` and `completefunc`.

**Comment by girishji** [comment]
See PR #332
