### ISSUE TITLE
Semantic Tokens support

### ISSUE THREAD

**Issue by Tachi107** [yegappan/lsp#126]
Hi, LSP 3.16 introduced [Semantic Tokens](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_semanticTokens), a way to provide nice syntax highlighting.

I'm aware that the vim9 lsp plugin [does not currently support](https://github.com/yegappan/lsp/blob/f5386053fd05d64edd0117c3add980fc5d85d095/autoload/lsp/handlers.vim#L165) this, so I'm opening this issue as a feature request.

Some similar LSP plugins support this feature; it may be helpful to look at how they are implemented:

- NeoVim: <https://github.com/neovim/neovim/pull/21100>
- vim-lsp: <https://github.com/prabirshrestha/vim-lsp/pull/1275>

**Comment by Tachi107** [comment]
It seems that commit 9bfc47d00b13686088a81e518704934bb9327edc added "initial support" for semantic tokens - great! How "initial" is this support? Is it known to work reliably? If that's the case, we could close this issue :)

**Comment by yegappan** [comment]
The semantic tokens support should work reliably.  If you see any issues, please open a issue.  I will close this issue.
