### ISSUE TITLE
processWorkspaceSymbolReply: E1012

### ISSUE THREAD

**Issue by Shane-XB-Qian** [yegappan/lsp#13]
```vim
  for symbol in reply.result
    if !symbol->has_key('location')
```
of `processWorkspaceSymbolReply`, that `reply.result` maybe a `special` type, but here needs a `list<any>`. so E1012.

// actually, perhaps better check all those funcs in `ProcessReply`, check their type, not only if `empty()`.
```vim
  if lsp_reply_handlers->has_key(req.method)
    lsp_reply_handlers[req.method](lspserver, req, reply)
  else
```
of `def ProcessReply`, perhaps can check there in totally, that `replay`.

**Comment by yegappan** [comment]
I have committed the check for the reply.result type as part of b7cc5a2f4477f16c1eaeb9f32785c3426134123c.

**Comment by Shane-XB-Qian** [comment]
verified. thx.
