### ISSUE TITLE
Double dollar sign insertion

### ISSUE THREAD

**Issue by noorwachid** [yegappan/lsp#130]
https://user-images.githubusercontent.com/42460975/211540929-04ec095d-cb95-474a-b843-4d82bfd5d72b.mov

**Comment by andlrc** [comment]
What language is this? What language server is used? And how is it configured?

**Comment by andlrc** [comment]
Seems like it's related to #143

**Comment by yegappan** [comment]
I think this is PHP.  Can you attach the complete code sample, so that it will be easier to reproduce the problem?  Can you also mention the language server name?

**Comment by yegappan** [comment]
Few changes are recently made to the completion code.  Can you try to reproduce this problem with the latest version of the plugin?

**Comment by noorwachid** [comment]
Status: Still occuring
Vim: 9
Plugin: Latest Version
Language: PHP
LSP: intelephense

``` php
<?php 

$long_variable_name = 'noorwachid';

$$long_variable_name 
```

https://user-images.githubusercontent.com/42460975/225661965-2894160c-7d30-4f1a-a5bc-3264e7bf0316.mov

**Comment by andlrc** [comment]
@noorwachid I think the following diff might solve your problem, but I'm not sure how it will behave in other cases:

```
diff --git a/autoload/lsp/completion.vim b/autoload/lsp/completion.vim
index 8ab8d6b..7c25f8d 100644
--- a/autoload/lsp/completion.vim
+++ b/autoload/lsp/completion.vim
@@ -90,12 +90,29 @@ export def CompletionReply(lspserver: dict<any>, cItems: any)
   var starttext = getline('.')[ : col - 1]
   var prefix = tolower(matchstr(starttext, '\k*$'))
 
+  var start_col: number = 0
+
+  # LSP server didn't return a starting position for completion, search
+  # backwards from the current cursor position for a non-keyword character.
+  if start_col == 0
+    var line: string = getline('.')
+    var start = col('.') - 1
+    while start > 0 && line[start - 1] =~ '\k'
+      start -= 1
+    endwhile
+    start_col = start + 1
+  endif
+
   var completeItems: list<dict<any>> = []
   for item in items
     var d: dict<any> = {}
     # TODO: Add proper support for item.textEdit.newText and item.textEdit.range
     # Keep in mind that item.textEdit.range can start be way before the typed keyword.
-    if item->has_key('insertText')
+    if item->has_key('textEdit')
+      var textEdit_start_col: number = util.GetLineByteFromPos(bufnr(), item.textEdit.range.start) + 1
+      var offset = start_col - textEdit_start_col
+      d.word = item.textEdit.newText[ offset : ]
+    elseif item->has_key('insertText')
       d.word = item.insertText
     else
       d.word = item.label
@@ -158,19 +175,6 @@ export def CompletionReply(lspserver: dict<any>, cItems: any)
       return
     endif
 
-    var start_col: number = 0
-
-    # LSP server didn't return a starting position for completion, search
-    # backwards from the current cursor position for a non-keyword character.
-    if start_col == 0
-      var line: string = getline('.')
-      var start = col('.') - 1
-      while start > 0 && line[start - 1] =~ '\k'
-	start -= 1
-      endwhile
-      start_col = start + 1
-    endif
-
     completeItems->complete(start_col)
   else
     lspserver.completeItems = completeItems
```

Is it possible for you to try it out? You can also find the code here: https://github.com/andlrc/lsp/tree/naive-attempt-to-support-textEdit Notice that the branch is "naive-attempt-to-support-textEdit".

**Comment by Shane-XB-Qian** [comment]
try PR #159

**Comment by yegappan** [comment]
According to the https://phpactor.readthedocs.io/en/master/lsp/vim.html page, to address this issue either '$' should be added to the 'iskeyword' option or "language_server_completion.trim_leading_dollar" should be set to true in the .phpactor.json file.

**Comment by Shane-XB-Qian** [comment]
> According to the https://phpactor.readthedocs.io/en/master/lsp/vim.html page, to address this issue either '$' should be added to the 'iskeyword' option or "language_server_completion.trim_leading_dollar" should be set to true in the .phpactor.json file.

seems latter one was a good option, but actually you will see others lsp server e.g ts may have '.foo' leading char in 'insertEdit',
so my pr/patch perhaps was required still.

-- 
shane.xb.qian

**Comment by andlrc** [comment]
> According to the https://phpactor.readthedocs.io/en/master/lsp/vim.html page, to address this issue either '$' should be added to the 'iskeyword' option or "language_server_completion.trim_leading_dollar" should be set to true in the .phpactor.json file.

I might be misunderstanding something, but I think OP is trying to use https://www.npmjs.com/package/intelephense
