### ISSUE TITLE
a missed code patch for hover doc.

### ISSUE THREAD

**Issue by Shane-XB-Qian** [yegappan/lsp#14]
![image](https://user-images.githubusercontent.com/13550529/111030467-635f6600-843d-11eb-92e1-b6356b26005e.png)

```patch
diff --git a/autoload/handlers.vim b/autoload/handlers.vim
index d94d59b..fa37e39 100644
--- a/autoload/handlers.vim
+++ b/autoload/handlers.vim
@@ -301,13 +301,13 @@ def s:processHoverReply(lspserver: dict<any>, req: dict<any>, reply: dict<any>):
       endif
     endfor
   elseif reply.result.contents->type() == v:t_string
     if reply.result.contents->empty()
       return
     endif
-    hoverText->add(reply.result.contents)
+    hoverText->extend(reply.result.contents->split("\n"))
   else
     ErrMsg('Error: Unsupported hover contents (' .. reply.result.contents .. ')')
     return
   endif
   hoverWinid = hoverText->popup_atcursor({moved: 'word'})
   if hoverWinid > 0
```

**Comment by yegappan** [comment]
I have committed this change as part of b7cc5a.

**Comment by Shane-XB-Qian** [comment]
verified. thx.
// just there is still a little flaw: hoverdoc maybe not empty, but after split -it is empty, e.g just '\n'. plus some ' '.
// - though not a big problem, but just a bit not perfect.. :-)
// and content maybe 'null', when lsp not ready or not complete or something, but that lsp actually supported that ft, maybe a bit not smooth..
// - maybe my suggested new 'function' in previous pr, perhaps better be added? :-) so user would know that ft actually support, just need to wait some seconds to let lsp to be ready.
