### ISSUE TITLE
Fuzzy search auto completion isn't working in `gopls`

### ISSUE THREAD

**Issue by andlrc** [yegappan/lsp#164]
This commit eb5ad92bf4b808c8295a1626c3ba9a74cfbf195c removes matches that doesn't start with the keyword prefix before cursor. Why is this needed? I think that by removing the else block fuzzy search in gopls would work.

Do you have a specific language server where this is needed?

**Comment by andlrc** [comment]
Please take a look at this recording, to see the difference:

https://asciinema.org/a/cryTKlg1ZIW5lITp2GH7XMH40

**Comment by yegappan** [comment]
I added the filtering to remove the completion matches that doesn't start with the prefix to deal with the Typescript/Javascript language server.  For example, if you use the following code snippet (a.js):

    const http = require('http')
    http.cre

With the cursor at the end "cre", if you type "a", then you will see the completion match "createServer".  Without the filtering, you will see many completion matches that doesn't start with the prefix "cre".

It looks like the Typescript/JavaScript language server expects the client to do the filtering.

**Comment by andlrc** [comment]
Oh got ya, for `autoCompletion=true`. I think we should add the same check for `isIncomplete` that  #163 adds

**Comment by andlrc** [comment]
Solved in #163
