### ISSUE TITLE
When there is only one completion, the completion will be missing in some cases 

### ISSUE THREAD

**Issue by ycycyyc** [yegappan/lsp#168]
The 'ignorecase' option is on, and I found that when I typed the full function name, the completion items were missing

![image](https://user-images.githubusercontent.com/30541266/226335652-408b2bc2-8648-4719-a9a6-e38bc4719cfe.png)

![image](https://user-images.githubusercontent.com/30541266/226335693-65168207-f8d1-4a28-a441-6f179b8a49e7.png)

https://github.com/yegappan/lsp/blob/main/autoload/lsp/completion.vim#L182
The code returns from here, but actually the match fails.I had to remove this code.

It might be better to use the stridx function instead of matchstr

**Comment by andlrc** [comment]
Hey, you are welcome to leave a PR. It's currently a bit of a mess as to where case folding is support and where it isn't. Some language servers also filters the results while other relay on the client to do the filtering.

Bottom line is that I think a small PR modifying the behavior when one item is left would be approved.

**Comment by yegappan** [comment]
In the above screenshot, it looks like the completion match (testFunc) is properly shown in the completion popup.  After you typed the complete function name, why do you need the completion popup?  Do you expect the popup to continue to show after typing the entire function name?

**Comment by Tachi107** [comment]
> Do you expect the popup to continue to show after typing the complete function name? In this example, the typed function name (testfunc) matches the completion match (testFunc) completely, so the completion popup will not be displayed.

I would. The function name matches the completion search, but it isn't the actual true function name, and still having the completion  popup in such a case would be helpful, in my opinion

**Comment by andlrc** [comment]
> I would. The function name matches the completion search, but it isn't the actual true function name, and still having the completion popup in such a case would be helpful, in my opinion

Force matching case in `matchstr` might be a solution:

```
diff --git a/autoload/lsp/completion.vim b/autoload/lsp/completion.vim
index 04e92fa..fe9799d 100644
--- a/autoload/lsp/completion.vim
+++ b/autoload/lsp/completion.vim
@@ -179,7 +179,7 @@ export def CompletionReply(lspserver: dict<any>, cItems: any)
     endif
 
     if completeItems->len() == 1
-	&& getline('.')->matchstr($'{completeItems[0].word}\>') != ''
+	&& getline('.')->matchstr($'\C{completeItems[0].word}\>') != ''
       # only one complete match. No need to show the completion popup
       return
     endif
```

Another approach would be to update the line with the properly cased match, something like this:

```
diff --git a/autoload/lsp/completion.vim b/autoload/lsp/completion.vim
index 04e92fa..d1a2f68 100644
--- a/autoload/lsp/completion.vim
+++ b/autoload/lsp/completion.vim
@@ -180,6 +180,7 @@ export def CompletionReply(lspserver: dict<any>, cItems: any)
 
     if completeItems->len() == 1
 	&& getline('.')->matchstr($'{completeItems[0].word}\>') != ''
+      setline('.', getline('.')->substitute($'{completeItems[0].word}\>', completeItems[0].word, ''))
       # only one complete match. No need to show the completion popup
       return
     endif
```

**Comment by yegappan** [comment]
Can you create a PR with the first approach (using \C to match case)?

**Comment by ycycyyc** [comment]
Thank you for your suggestions, and it actually worked.
I create a PR: https://github.com/yegappan/lsp/pull/170

**Comment by Tachi107** [comment]
Thanks!
