### ISSUE TITLE
Notice: 'ProcessMessages' had E488.

### ISSUE THREAD

**Issue by Shane-XB-Qian** [yegappan/lsp#2]
a headsup notice: 

    var content = lspserver.data[idx : idx + len - 1]
    var msg = content->json_decode()

looks sometime ‘lsp.data->len - idx < len’ such judgement not good enough or somehow, that process json decode would raised e488 err,
But cannot solid reproduced, just a note...

**Comment by yegappan** [comment]
Thanks for the report. Which language server are you using? Can you include the complete error message?

**Comment by Shane-XB-Qian** [comment]
so far only tried 'bash'
![image](https://user-images.githubusercontent.com/13550529/108803044-a95ea200-75d4-11eb-9612-9c5c3b5656d6.png)

**Comment by Shane-XB-Qian** [comment]
perhaps should not use `lspserver.data->len()` in `while` loop, since that's a 'cb', data may change.. I Guess.
// meanwhile vim9 looks had massive bug for now, v8.2.2543 looks till now didnot handle try/catch well............. :-)

**Comment by Shane-XB-Qian** [comment]
tried 'java', looks java lsp had more capability than 'bash':
![image](https://user-images.githubusercontent.com/13550529/108998929-920adc00-76dc-11eb-83ee-bb55dded8fa5.png)
though those msg did not supported by this plugin yet, but looks above E488 issue was happening when lsp was not ready.

**Comment by Shane-XB-Qian** [comment]
notice: those all just is a FYI, did not expect you had to fix it.. or pls thought those not a bug but a enhancement, perhaps.. thx. :-)

**Comment by Shane-XB-Qian** [comment]
![image](https://user-images.githubusercontent.com/13550529/109110485-3854f100-7772-11eb-8db2-a5b71e89c353.png)
// and this, i hear there is LSP 3.0, not sure if that is.

**Comment by yegappan** [comment]
The LSP plugin supports LSP protocol version 3.6. It looks like the Java language server doesn't support the LSP 3.0 protocol and is written for an older version of the protocol. Which Java language server are you using?

**Comment by Shane-XB-Qian** [comment]
On 21/02/26 08:58AM, Yegappan Lakshmanan wrote:
> The LSP plugin supports LSP protocol version 3.6. It looks like the Java language server doesn't support the LSP 3.0 protocol and is written for an older version of the protocol. Which Java language server are you using?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/yegappan/lsp/issues/2#issuecomment-786768290

it is jdtls from eclipse.

// above E488 err for 'bash', still no clear clue, but just suddenly
// happened, I Guess the cause was like above, pls help investigate if
// you have time... :-)

-- 
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
perhaps should add try/catch to `msg = content->json_decode()` ?
// perhaps would make some msg lost if so, but can add some gentle warning msg instead of err. 
that err looks some content was not complete or fmt/encoding cannot be 'json' decode..
// if specific to bash lsp, then that lsp server would scan all sh type fs under cur, that may cost much if opened a foo.sh under HOME.

**Comment by yegappan** [comment]
Yes. When I tried to handle the exceptions in decoding the LSP server message, I ran into a bug in Vim and reported it and is now addressed by 8.2.2602. I am trying to the handle various errors that can happen with the LSP server message.

**Comment by Shane-XB-Qian** [comment]
Great! looks we (mainly by you :-)) solved a big mess in vim9.. :rofl: 
// verified. and perhaps better to mention '8.2.2602' was the preferred version of vim in doc/readme.
// closing this ticket now.
