### ISSUE TITLE
Any Ruby LSP and Deno LSP doesn't work 

### ISSUE THREAD

**Issue by maximyurevich** [yegappan/lsp#218]

**Comment by yegappan** [comment]
I am able to successfully use the solargraph Ruby LSP server.  How did you add the solargraph server to the LSP plugin?

**Comment by maximyurevich** [comment]
> I am able to successfully use the solargraph Ruby LSP server. How did you add the solargraph server to the LSP plugin?

```vim
{
  'name': 'rubylang',
  'filetype': ['ruby'],
  'path': 'solargraph',
  'args': ['stdio']
}
```

**Comment by maximyurevich** [comment]
> I am able to successfully use the solargraph Ruby LSP server. How did you add the solargraph server to the LSP plugin?

After deleting vim-lsp-settings-adapter ыolargraph started working but I got the following error

https://user-images.githubusercontent.com/21293376/230580321-afc9d75b-c065-456c-a311-18e2f314c868.mp4

**Comment by maximyurevich** [comment]
And Deno LSP started working after adding initOptions

**Comment by yegappan** [comment]
The Solargraph language server returns null as the "detail" field for some of the completion items.  I have pushed fcbe77b3884517a84d8ce5331b14da24b3bf4678 to properly handle this.  Can you try using the latest plugin?
