### ISSUE TITLE
Support html and css

### ISSUE THREAD

**Issue by maximyurevich** [yegappan/lsp#219]

**Comment by yegappan** [comment]
Are you looking for the HTML/CSS language server support?  Which language server are you referring to?

**Comment by yegappan** [comment]
I am able to use the HTML language server using the following lines:

    call LspAddServer([#{name: 'htmlls',
                     \   filetype: 'html',
                     \   path: '/usr/local/node_modules/.bin/html-languageserver',
                     \   args: ['--stdio']
                     \ }])

**Comment by maximyurevich** [comment]
> call LspAddServer([#{name: 'htmlls',
>                  \   filetype: 'html',
>                  \   path: '/usr/local/node_modules/.bin/html-languageserver',
>                  \   args: ['--stdio']
>                  \ }])
> 
> call LspAddServer([#{name: 'cssls',
>                  \   filetype: 'css',
>                  \   path: '/usr/local/node_modules/.bin/css-languageserver',
>                  \   args: ['--stdio']
>                  \ }])

i don't get autocomplete for both, diagnostics only from css-languageserver

**Comment by yegappan** [comment]
I am able to get autocompletion with both the HTML and the CSS language server.  Can you give a sample HTML or CSS code where autocomplete is not working?

**Comment by maximyurevich** [comment]
> I am able to get autocompletion with both the HTML and the CSS language server. Can you give a sample HTML or CSS code where autocomplete is not working?

https://user-images.githubusercontent.com/21293376/230680182-deafddf4-ab23-4232-b42b-93e54e79c41c.mp4

**Comment by andlrc** [comment]
> I am able to get autocompletion with both the HTML and the CSS language server. Can you give a sample HTML or CSS code where autocomplete is not working?

For me none of the two servers installed via npm are completion providers.

@maximyurevich what is the output of `:LspShowServerCapabilities`?

**Comment by yegappan** [comment]
The output of the `:LspShowServerCapabilities` command in my setup is:

```
colorProvider: {}
completionProvider: {'resolveProvider': true, 'triggerCharacters': ['.', ':', '<', '"', '=', '/']}
definitionProvider: true
documentHighlightProvider: true
documentLinkProvider: {'resolveProvider': false}
documentRangeFormattingProvider: false
documentSymbolProvider: true
foldingRangeProvider: true
hoverProvider: true
referencesProvider: true
signatureHelpProvider: {'triggerCharacters': ['(']}
textDocumentSync: 1
```

**Comment by maximyurevich** [comment]
HTML

> > I am able to get autocompletion with both the HTML and the CSS language server. Can you give a sample HTML or CSS code where autocomplete is not working?
> 
> For me none of the two servers installed via npm are completion providers.
> 
> @maximyurevich what is the output of `:LspShowServerCapabilities`?

![Screenshot_2023-04-08_00-53-11](https://user-images.githubusercontent.com/21293376/230683640-c3317c76-34b5-4753-bece-1a3048f12902.png)

**Comment by andlrc** [comment]
Interestingly enough setting `g:LspOptionsSet(#{ snippetSupport: v:true })` will get the HTML language server to report that they support completions 🤷

**Comment by yegappan** [comment]
That is weird.  The following code confirms your finding:

https://github.com/vscode-langservers/vscode-html-languageserver/blob/18bed63e90d661407306d3b66a856e951036567d/src/htmlServerMain.ts#L125

Every language server has some unique behavior :disappointed:.

**Comment by yegappan** [comment]
I have created the following page to capture language server specific configuration and notes:

https://github.com/yegappan/lsp/wiki
