### ISSUE TITLE
Padding of virtual text for diagnostics is wrong if tabs are used within in the text

### ISSUE THREAD

**Issue by berggeist** [yegappan/lsp#220]
There seems to be a bug within the padding of virtual text for diagnostic messages if tab characters are used in the source code.
In the following screenshot, the left corner of the diagnostic message should be aligned to column 9, right above the first character **f** within _fmt.Printf_. Instead, it is aligned incorrectly to column 2.

![vim-lsp-virtual-text-tabs-wrong](https://user-images.githubusercontent.com/24396556/230606842-56e6c514-4618-4497-b121-7dd8b202c4ad.png)

The correct behavior should be like in the following screenshot:
 
![vim-lsp-virtualtext-tab-correct](https://user-images.githubusercontent.com/24396556/230607119-491c1b51-c267-4425-85a4-01edbb0555b3.png)

The problem seems to be that for the padding the attribute **diag.range.start.character** is used and this attribute holds the value 1, i.e. for one tab character.
In the corrected screenshot the real display width is being used for calculating the padding with **strdisplaywidth()**, by applying the following patch:

``` vim
diff --git a/autoload/lsp/diag.vim b/autoload/lsp/diag.vim
index c0dffc4..805e7c8 100644
--- a/autoload/lsp/diag.vim
+++ b/autoload/lsp/diag.vim@@ -137,11 +137,16
@@ def DiagsRefreshSigns(lspserver: dict<any>, bnr: number)
       endif

       if opt.lspOptions.showDiagWithVirtualText
+        var padding = diag.range.start.character
+        if padding > 0
+          padding = strdisplaywidth(getline(diag.range.start.line + 1)[ : diag.range.start.character - 1])
+        endif
         prop_add(lnum, 0, {bufnr: bnr,
                            type: 'LspDiagVirtualText',
                            text: $'┌─ {diag.message}',
                            text_align: 'above',
-                           text_padding_left: diag.range.start.character})
+                           text_padding_left: padding})
       endif
```

Especially when programming in the go programming language this is an issue, because the go-lsp-formatter insists on using tab characters for indentation.

**Comment by yegappan** [comment]
Thanks for reporting the issue with a patch.  Can you create a PR with this change?

**Comment by berggeist** [comment]
You're welcome. I would like to thank you for this great vim plugin.
Never made a PR up to now, but I'll try my best. Just give me a little time :-)

**Comment by berggeist** [comment]
Just verified that with the merge of PR #222  this lsp issue is solved.
