### ISSUE TITLE
root uri option

### ISSUE THREAD

**Issue by maximyurevich** [yegappan/lsp#221]
I want to use Deno LSP and TypeScript LSP and I don't want to run those LSPs at the same time. vim-lsp has this option, for example: https://github.com/prabirshrestha/vim-lsp/wiki/Servers-TypeScript

**Comment by yegappan** [comment]
I have committed ca7f26773bf4348d956e16d3d9dba82ca87c180c to support detecting the workspace root directory given a list of files.  When registering the LSP server, you need to specify a List of file and directory names using the 'rootSearch' item.  Can you try this out?

**Comment by andlrc** [comment]
> Can you try this out?

Really nice feature 🎉 It works for me, only complain is the new default for `rootUri`, see #224

**Comment by Shane-XB-Qian** [comment]
another thinking: 
if one file opened under /home/xxx which there massive files, do we need to prevent pc hang or lsp over workload?

**Comment by yegappan** [comment]
>
> if one file opened under /home/xxx which there massive files, do we need to prevent pc hang or lsp over workload?
>

How will the search for a parent directory containing a specific file hang the system?  Are you referring to a very deep directory tree structure?  I can see that in a NFS mounted file system, the search will be relatively slow.  But this is done only once when
starting a LSP server.

**Comment by Shane-XB-Qian** [comment]
e.g indexing.
obviously if you open a dumb foo.xx under /home/xxx, that would search whole subdir and including dirs.
for such case, do we need to limit only for that opened file, or whatever that's lsp server's job.

**Comment by maximyurevich** [comment]
> I have committed [ca7f267](https://github.com/yegappan/lsp/commit/ca7f26773bf4348d956e16d3d9dba82ca87c180c) to support detecting the workspace root directory given a list of file and directory names. When registering the LSP server, you need to specify a List of file and directory names using the 'rootSearch' item. Can you try this out?

can you please provide example, my configuration not work
https://i.imgur.com/6hX1juj.png

**Comment by andlrc** [comment]
@maximyurevich it works for me, can you enable debug, see `:h lsp-debug` please use the `debug: v:true` approach as it should enable debugging before the initialization step.

Then after the server is started you should post the result of `:LspServerDebug messages`.

**Comment by maximyurevich** [comment]
[lsp-typescript.log](https://github.com/yegappan/lsp/files/11183999/lsp-typescript.log)
Folder with deno.json file in root

**Comment by andlrc** [comment]
@maximyurevich I think that I start to understand what you want, you want to start the dino lsp when dino.json is located within the parent directories and the typescript-language-server when package.json is located in the parent directories? Currently it's only supported to add one server for a given filetype. And even the changes made in [ca7f267](https://github.com/yegappan/lsp/commit/ca7f26773bf4348d956e16d3d9dba82ca87c180c) will not make such a detection possible.

**Comment by maximyurevich** [comment]
> @maximyurevich I think that I start to understand what you want, you want to start the dino lsp when dino.json is located within the parent directories and the typescript-language-server when package.json is located in the parent directories? Currently it's only supported to add one server for a given filetype. And even the changes made in [ca7f267](https://github.com/yegappan/lsp/commit/ca7f26773bf4348d956e16d3d9dba82ca87c180c) will not make such a detection possible.

yes, I want this behavior

**Comment by andlrc** [comment]
@maximyurevich can you try out this PR and see if it does what you expect? https://github.com/yegappan/lsp/pull/225

**Comment by maximyurevich** [comment]
> @maximyurevich can you try out this PR and see if it does what you expect? #225

yes, this work

**Comment by maximyurevich** [comment]
@yegappan please check @andlrc PR for close this issue
