### ISSUE TITLE
snippetSupport: v:true and friendly snippets 

### ISSUE THREAD

**Issue by maximyurevich** [yegappan/lsp#232]
Hello, I can't get to work "friendly-snippets" plugin completion preview with vsnip and vsnip-integ.

**Comment by maximyurevich** [comment]
@yegappan can you please provide your lspOptions and completion keybinds, because I dont know whats wrong with my config, just ultisnips works

**Comment by Shane-XB-Qian** [comment]
could you not open dup issue (this one same like #124 which also opened by you).
// and #182 

vsnip-integ is not a plugin not provided by this author, maybe you can ask that plugin author gave some advice to integ.

**Comment by maximyurevich** [comment]
> could you not open dup issue (this one same like #124 which also opened by you). // and #182
> 
> vsnip-integ is not a plugin not provided by this author, maybe you can ask that plugin author gave some advice to integ.

ok

**Comment by Shane-XB-Qian** [comment]
thx. if he gave some advice or did some enhance something to vsnip-integ, wish you can give feedback to #124 or #182 as well.
