### ISSUE TITLE
type mis-match

### ISSUE THREAD

**Issue by Shane-XB-Qian** [yegappan/lsp#24]
chg from pr ea1020b5 : 
autoload/handlers.vim
line#138
        label = sig.parameters[result.activeParameter].documentation

`E1012: Type mismatch; expected string but got special`

// by the way:  the doc about 'setOption', the key should add quote.
line# 252 and 259
e.g 
`			    call lsp#setOptions({showSignature: v:false})`

**Comment by Shane-XB-Qian** [comment]
autoload/handlers.vim

**Comment by yegappan** [comment]
I have pushed a commit to fix this issue. Can you try the latest version of the plugin?
Thanks

**Comment by Shane-XB-Qian** [comment]
yes, err is gone.
but:
1, what if `sig.parameters[result.activeParameter]->has_key('documentation')` is true -but- it was not a `v:string`?
2, the indent of those lines looks a bit mess.
