### ISSUE TITLE
automatic imports are duplicating

### ISSUE THREAD

**Issue by D4yvid** [yegappan/lsp#259]
When i try to auto-import a element using the autocompletion, it will duplicate the import.
Tested on:
  - clangd
  - jdt.ls

Vim on version 9.0.1321
yegappan/lsp at 69ae9e5
clangd on version 15.0.7

**Comment by andlrc** [comment]
Do you have a snippet plugin? I think you should set the option `completionTextEdit`, see `:h lsp-opt-completionTextEdit`:

```
						*lsp-opt-completionTextEdit*
completionTextEdit	|Boolean| option.  If true, apply the LSP server
			supplied text edits after a completion.  If a snippet
			plugin is going to apply the text edits, then set
			this to false to avoid applying the text edits twice.
			By default this is set to true.

```

**Comment by Shane-XB-Qian** [comment]
@D4yvid dup issue #233
