### ISSUE TITLE
eslint language server

### ISSUE THREAD

**Issue by sparkcanon** [yegappan/lsp#26]
I tried adding eslint language server as below but it seems not supported yet.

```
let lspServers = [
		\     {
		\	'filetype': ['javascript', 'typescript', 'javascriptreact'],
		\	'path': 'path/to/typescript-language-server',
		\	'args': ['--stdio']
		\     },
		\     {
		\	'filetype': ['javascript', 'typescript', 'javascriptreact'],
		\	'path': 'path/to/vscode-eslint-language-server',
		\	'args': ['--stdio']
		\     },
		\   ]
call lsp#addServer(lspServers)
```
Error I get:
```
Error: LSP server does not support getting list of symbols
Error: Unsupported request message received from the LSP server (<path to server>), message = {'id':
 0, 'jsonrpc': '2.0', 'method': 'workspace/configuration', 'params': {'items': [{'section': '', 'scopeUri': '<path>'}]}}
```

I am not sure if this is a language server limitation or this plugin.

**Comment by hemangjoshi37a** [comment]
Have you found any solution to this yet? If yes please let me know

**Comment by yegappan** [comment]
The LSP plugin currently supports attaching only one language server to a Vim buffer/file.  The support for attaching multiple language servers to a buffer needs to be added.

**Comment by hemangjoshi37a** [comment]
Ok

**Comment by andlrc** [comment]
@hemangjoshi37a support have now been added to run multiple language servers at once, but I'm not sure vscode-eslint-language-server is supported. For what it is worth you could try [efm-langserver](https://github.com/mattn/efm-langserver) and run eslint that way.

**Comment by hemangjoshi37a** [comment]
The vscode-eslint-language-server is not a standalone package that can be installed via npm. It is a part of the vscode-eslint extension, which is specifically designed to work with Visual Studio Code.

To use ESLint with a language server like efm-langserver, you can follow these steps:

1. Install efm-langserver if you haven't already:
```bash
go get -u github.com/mattn/efm-langserver
```
Make sure you have the Go programming language installed before running this command.

2. Install ESLint:
```bash
npm install -g eslint
```
3. Create an .eslintrc configuration file in your project root or set up ESLint according to your preferences.

4. Configure your editor or IDE to use efm-langserver. The configuration varies depending on the editor you are using. Here's an example configuration for Neovim with the coc.nvim extension:

```json
{
  "languageserver": {
    "efm": {
      "command": "efm-langserver",
      "args": [],
      "filetypes": ["javascript", "typescript"],
      "initializationOptions": {
        "documentFormatting": true
      },
      "settings": {
        "languages": {
          "javascript": [
            {
              "lintCommand": "eslint -f unix --stdin --stdin-filename ${INPUT}",
              "lintStdin": true,
              "lintFormats": ["%f:%l:%c: %m"],
              "formatCommand": "eslint --fix-to-stdout --stdin --stdin-filename=${INPUT}",
              "formatStdin": true
            }
          ],
          "typescript": [
            {
              "lintCommand": "eslint -f unix --stdin --stdin-filename ${INPUT}",
              "lintStdin": true,
              "lintFormats": ["%f:%l:%c: %m"],
              "formatCommand": "eslint --fix-to-stdout --stdin --stdin-filename=${INPUT}",
              "formatStdin": true
            }
          ]
        }
      }
    }
  }
}
```
Replace the configuration in your editor with the appropriate configuration for your specific setup. This should allow you to use ESLint through the efm-langserver.

**Comment by andlrc** [comment]
Maybe this information about efm-langserver could be added to the wiki?

**Comment by yegappan** [comment]
I have updated the Wiki page with this information.  I didn't try the efm language server.  So I don't know whether it works properly or not.

**Comment by hemangjoshi37a** [comment]
> Maybe this information about efm-langserver could be added to the wiki?

@andlrc  yes that is a good idea .

**Comment by andlrc** [comment]
@yegappan I think that you need to add a settings object as well:

```

		 \   workspaceConfig: #{
		 \     languages: #{
```

Should be:

```

		 \   workspaceConfig: #{
		 \     settings: #{
		 \       languages: #{
```

I base this on this part from the source code: https://github.com/mattn/efm-langserver/blob/master/langserver/handle_workspace_did_change_configuration.go#L21

**Comment by yegappan** [comment]
The plugin sends the items under "workspaceConfig" in a "settings" Dict in the message.  I have verified that the example in the Wiki page works with the efm language server.

**Comment by hemangjoshi37a** [comment]
@yegappan @andlrc

Thank you both for the detailed explanations and for your continuous support on this matter. This discussion about integrating `vscode-eslint-language-server` and `efm-langserver` provides valuable insights into the nuances of Language Server Protocols (LSP).

I'd like to contribute a few thoughts that could perhaps streamline the process and alleviate the issue at hand. 

Firstly, it's indeed correct that the `vscode-eslint-language-server` is embedded within the VS Code ESLint extension and is not directly installable via npm. This extension has been optimized for usage within the Visual Studio Code environment and it might pose challenges to make it work outside its designed ecosystem. 

In light of this, I believe the usage of `efm-langserver` is a more feasible option as it has been designed to work with multiple languages and tools, including ESLint. By utilizing `efm-langserver`, we can bridge the gap between ESLint and any text editor or IDE that supports LSP. This flexibility of `efm-langserver` makes it a versatile tool for code linting and formatting.

Here's a sample configuration code for `efm-langserver` that might be helpful:

```json
{
  "languageserver": {
    "efm": {
      "command": "efm-langserver",
      "args": [],
      "filetypes": ["javascript", "typescript"],
      "initializationOptions": {
        "documentFormatting": true
      },
      "settings": {
        "languages": {
          "javascript": [
            {
              "lintCommand": "eslint -f unix --stdin --stdin-filename ${INPUT}",
              "lintStdin": true,
              "lintFormats": ["%f:%l:%c: %m"],
              "formatCommand": "eslint --fix-to-stdout --stdin --stdin-filename=${INPUT}",
              "formatStdin": true
            }
          ],
          "typescript": [
            {
              "lintCommand": "eslint -f unix --stdin --stdin-filename ${INPUT}",
              "lintStdin": true,
              "lintFormats": ["%f:%l:%c: %m"],
              "formatCommand": "eslint --fix-to-stdout --stdin --stdin-filename=${INPUT}",
              "formatStdin": true
            }
          ]
        }
      }
    }
  }
}
