### ISSUE TITLE
Can't get angular-language-server to work

### ISSUE THREAD

**Issue by MartinAskestad** [yegappan/lsp#268]
I'm trying to configure angular-language-server (@angular/language-server). But I run in to the issue that it thinks that I'm missing some kind of library and the correct version. But I should have the correct version installed. Perhaps I'm missing some argument or property in my config, but I can't quite figure out wich.

```Error: Failed to resolve 'typescript/lib/tsserverlibrary' with minimum version '4.8' from []
    at resolveWithMinVersion (C:\Users\m\scoop\persist\nodejs-lts\bin\node_modules\@angular\language-server\index.js:253:13)
    at resolveTsServer (C:\Users\m\scoop\persist\nodejs-lts\bin\node_modules\@angular\language-server\index.js:262:14)
    at requireOverride (C:\Users\m\scoop\persist\nodejs-lts\bin\node_modules\@angular\language-server\index.js:337:57)
    at ../../../../../../../../execroot/__main__/bazel-out/darwin-fastbuild/bin/server/src/logger.js (C:\Users\m\scoop\persist\nodejs-lts\bin\node_modules\@angular\language-server\index.js:482:27)
    at __require (C:\Users\m\scoop\persist\nodejs-lts\bin\node_modules\@angular\language-server\index.js:354:50)
    at Object.<anonymous> (C:\Users\m\scoop\persist\nodejs-lts\bin\node_modules\@angular\language-server\index.js:154270:16)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
C:\Users\m\scoop\persist\nodejs-lts\bin\node_modules\@angular\language-server\index.js:253
      throw new Error(`Failed to resolve '${packageName}' with minimum version '${minVersion}' from ` + JSON.stringify(probeLocations, null, 2));
      ^
```

**Comment by andlrc** [comment]
This is a configuration problem of the angular language server, you need to provide a few arguments to `ngserver`:

- `--stdio`,
- `--ngProbeLocations` I think this needs an argument to your global node_modules,
- and `--tsProbeLocations` I think this needs an argument to your local node_modules.

`ngserver` also sends quite a few notifications that aren't in the specifications, you can silence them by creating an dictionary called `customNotificationHandlers` that contains Funcref: 

The below is vim9 script, take a look at the README.md to see how it can be done in viml.

```viml
  customNotificationHandlers: {
    'angular/projectLoadingStart': (lspserver, reply) => {
    },
    'angular/projectLoadingFinish': (lspserver, reply) => {
    },
    'angular/projectLanguageService': (lspserver, reply) => {
    },
    'angular/NgccProgressEnd': (lspserver, reply) => {
    },
    'angular/suggestStrictMode': (lspserver, reply) => {
    }
  },
```

FWIW This is how I have configured `ngserver`, again in vim9script:

```viml
g:LspAddServer([{
  filetype: ['html'],
  path: 'ngserver',
  args: ['--stdio', '--ngProbeLocations', '/opt/homebrew/lib/node_modules', '--tsProbeLocations', '/path/to/angular/project'],
  customNotificationHandlers: {
  'angular/projectLoadingStart': (lspserver, reply) => {
    },
  'angular/projectLoadingFinish': (lspserver, reply) => {
    },
  'angular/projectLanguageService': (lspserver, reply) => {
    },
  'angular/NgccProgressEnd': (lspserver, reply) => {
    },
  'angular/suggestStrictMode': (lspserver, reply) => {
    }
  },
  rootSearch: ['.angular/'],
  runIfSearch: ['.angular/'],
}])
```

Hope it helps.

**Comment by MartinAskestad** [comment]
@andlrc Mange tak, but do I have to hard code the tsProbeLocations? I have a bunch of angular projects and updating my config every time I want to open another one seems inefficient.

**Comment by andlrc** [comment]
> @andlrc Mange tak, but do I have to hard code the tsProbeLocations?

I'm not sure exactly what `ngserver` expects. They are very friendly over at https://github.com/angular/vscode-ng-language-service if you wanna ask the developers about details.

Depending on how you open your project, you might be able to simply stick `getcwd() .. '/node_modules'` in as the argument. `getcwd()` returns the current working directory.  You can also utilize the util function from this library called: `FindNearestRootDir` which searches upwards a directory and tries to locate files:

```viml

vim9script

import autoload 'lsp/util.vim'

var tsProbeLocations = util.FindNearestRootDir(
  getcwd(),
  ['node_modules/', 'package.json', 'whatever_file', 'whatever_directory/']
)
if tsProbeLocations->empty()
  tsProbeLocations = getcwd()
endif

g:LspAddServer([{
  filetype: ['html'],
  path: 'ngserver',
  args: ['--stdio', '--ngProbeLocations', '/opt/homebrew/lib/node_modules', '--tsProbeLocations', tsProbeLocations],
  ...
```

**Comment by MartinAskestad** [comment]
I got it to work, but had to install `@angular/language-server` locally in my project as well as globally. I suppose I could make a vim-script that detects if it's locally installed and run `npm i` if needed.

**Comment by andlrc** [comment]
Happy that you got it working

**Comment by Shane-XB-Qian** [comment]
@MartinAskestad if you figured out the way perhaps wish you could or please update the wiki, there some config notes already.

**Comment by MartinAskestad** [comment]
@Shane-XB-Qian I keep getting a 403 when trying to update the wiki.

**Comment by Shane-XB-Qian** [comment]
um.. can you can clone to your local, then perhaps PR like general?

actually i am not sure general users can update it, or only owner?
if yes, then just point out the summary, let @yegappan help you update wiki.

**Comment by MartinAskestad** [comment]
@yegappan I can't quite figure out how to update the wiki with example of angular-language-server, I'll post it here. You can add it to the wiki if you want to.

Prerequisites: Do a `npm install -g @angular/language-server @angular/language-service typescript`

Then add this to your vimrc
```vim
call lsp#lsp#AddServer([{ 'name': 'angular', 'filetype': 'html', 'path': expand('$HOME/scoop/apps/nodejs-lts/current/bin/ngserver.cmd'),
			\ 'args': ['--ngProbeLocations', expand('$HOME/scoop/apps/nodejs-lts/current/bin/@angular/language-service'), '--tsProbeLocations', expand('$HOME/scoop/apps/nodejs-lts/current/bin/typescript'), '--stdio']}])
```

I'm using Windows by the way

**Comment by yegappan** [comment]
Thanks.  I have updated the Wiki with your steps to add the angular language server.  Let me know if any update is needed.
