### ISSUE TITLE
solargraph error

### ISSUE THREAD

**Issue by maximyurevich** [yegappan/lsp#271]
6 sec.

https://user-images.githubusercontent.com/21293376/232320880-d681dce6-09ed-406c-8e63-2f67f464671d.mp4

**Comment by andlrc** [comment]
I bet it's because you have configured the LSP server twice, or configured two servers with the same name.

**Comment by maximyurevich** [comment]
> I bet it's because you have configured the LSP server twice, or configured two servers with the same name.

Yes )
