### ISSUE TITLE
Respect `CompletionItem.sortText`

### ISSUE THREAD

**Issue by lithammer** [yegappan/lsp#281]
I think completion result should be sorted according to `sortText`. It's especially evident when using a Python language server since it will put "dunder methods" (e.g. `__str__`) first in the completion list otherwise.

I quickly hacked something together that seems to do the trick. But isn't super tested. [Similar to what vim-lsp does](https://github.com/prabirshrestha/vim-lsp/blob/80644e108b71d8735ab4c03dbc53db5ec6598d9b/autoload/lsp/omni.vim#L244-L257).

```diff
diff --git a/autoload/lsp/completion.vim b/autoload/lsp/completion.vim
index 938e55a..4ed7067 100644
--- a/autoload/lsp/completion.vim
+++ b/autoload/lsp/completion.vim
@@ -255,10 +255,21 @@ export def CompletionReply(lspserver: dict<any>, cItems: any)
       endif
     endif

+    d.score = item->get('sortText')
+    if empty(d.score)
+      d.score = item->get('label', '')
+    endif
+
     d.user_data = item
     completeItems->add(d)
   endfor

+  if opt.lspOptions.completionMatcher == 'icase'
+    sort(completeItems, (a, b) => a.score ==? b.score ? 0 : a.score >? b.score ? 1 : -1)
+  else
+    sort(completeItems, (a, b) => a.score ==# b.score ? 0 : a.score ># b.score ? 1 : -1)
+  endif
+
   if opt.lspOptions.autoComplete && !lspserver.omniCompletePending
     if completeItems->empty()
       # no matches
```

```js
/**
* A string that should be used when comparing this item
* with other items. When omitted the label is used
* as the sort text for this item.
*/
sortText?: string;
```

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem

**Comment by andlrc** [comment]
>  It's especially evident when using a Python language server since it will put "dunder methods" (e.g. __str__) first in the completion list otherwise.

I can't really replicate what you mention with `__str__`. Not for "autoComplete" nor for omni completion.

I think it makes sense to respect the given `sortText` though. If you create a PR I'm sure that it will be merged.

> I quickly hacked something together that seems to do the trick. But isn't super tested.

It's really hard to add a proper test for this without relaying on internals from a given language server. 

One more observation is that with `{ autoComplete: false, completionMatcher: 'fuzzy' }`, the items will not be sorted with respect for `sortText` but rather `matchfuzzy()` will sort them.

**Comment by lithammer** [comment]
> > It's especially evident when using a Python language server since it will put "dunder methods" (e.g. `__str__`) first in the completion list otherwise.
> 
> I can't really replicate what you mention with `__str__`. Not for "autoComplete" nor for omni completion.

Try this (cursor at `|`). It should list a bunch of things like `__name__` and `__package__` etc     first. This is using [Pyright](https://github.com/microsoft/pyright).

```python
import re
re.|
```

<img width="108" alt="image" src="https://user-images.githubusercontent.com/177685/233322655-0f501bd1-26df-43fc-88a6-a03011d2df34.png">

> I think it makes sense to respect the given `sortText` though. If you create a PR I'm sure that it will be merged.
> 
> > I quickly hacked something together that seems to do the trick. But isn't super tested.
> 
> It's really hard to add a proper test for this without relaying on internals from a given language server.

It's a bit unfortunate that the spec doesn't really say how you should use `sortText`. But it seems like you should just do a lexicographic sort since it's a string. And the servers usually do something like prefixing a bunch of numbers to simulate priority. So `__str__` would be `12345__str__`.

So given this, we could just test the sort function in isolation by breaking it out into its own function rather than a lambda.

> One more observation is that with `{ autoComplete: false, completionMatcher: 'fuzzy' }`, the items will not be sorted with respect for `sortText` but rather `matchfuzzy()` will sort them.

Good point.

**Comment by andlrc** [comment]
> This is using [Pyright](https://github.com/microsoft/pyright).

Makes sense, I tried it with pylsp, which I think this this one: https://github.com/python-lsp/python-lsp-server, but I don't know tbh, as I don't write any Python code myself.

**Comment by Shane-XB-Qian** [comment]
pyright may had sort items in server side, 
vs/but pylsp the received sortText is not empty, and specially looks some no sense chars, not sure how that worked.

**Comment by Shane-XB-Qian** [comment]
ohh, seems it put `__xx__`  kind items with a prefix `z`, vs/but normally items with `a`, so `__xx__` were sorted at last.
but @lithammer your patch perhaps should count kind with it, same kind should sort together.

**Comment by Shane-XB-Qian** [comment]
ohh, seems it put `__xx__`  kind items with a prefix `z`, vs/but normally items with `a`, so `__xx__` were sorted at last.
but @lithammer your patch perhaps should count kind with it, same kind should sort together.

**Comment by andlrc** [comment]
> > but @lithammer your patch perhaps should count kind with it, same kind should sort together.
> 
> Are you sure? VS Code seem to mix kinds:

I think we should respect `sortText` when set, and not try do any other sorting. Possible getting the items sorted by `matchfuzzy` if fuzzy matcher is enabled (just like omni completion does it now).

**Comment by Shane-XB-Qian** [comment]
@lithammer i am not sure, but vsc seems used pyright (or pylance) too.
to pylsp seems it had been sorted, just `__xx__` plus with `z` (prefix with it) so it sorted & placed at last.
so if you like to sort it, perhaps sort it with kind, otherwise it worked like that already (except `asc` vs `desc`)

**Comment by Shane-XB-Qian** [comment]
i meant even applied your patch but/if worked on pylsp and its sorttext, 
then it would sort/place __xxx__ such things at *last which looks not match your original demand (sort/place __xxx__ at *first).
// you can try your patch on pylsp, i just did a guess on what code/value logic, but did not really impl it.

**Comment by lithammer** [comment]
> This make sense. Can you create a PR with this change?

https://github.com/yegappan/lsp/pull/282

**Comment by Shane-XB-Qian** [comment]
![image](https://user-images.githubusercontent.com/13550529/233414328-147044c7-796f-46f5-bc48-65d9b2dd7852.png)

not sure if it was your demand, but anyway guess should be good for others' lsp.
