### ISSUE TITLE
Unable to start jdtls on Windows

### ISSUE THREAD

**Issue by Tachi107** [yegappan/lsp#285]
Hi all, I'm unable to start the jdtls language server on Windows. It works on Linux without issues, and starting `jdtls` on the command line works without issues, but when opening a .java file I see `Error: Failed to start LSP server jdtls`.

How can I debug the issue? Turning on the debug options for the LSP server doesn't help, since the plugin can't start the server at all.

    $ command -v jdtls
    C:/Users/tachi/Documents/programmi/bin/jdtls.bat

    $ cat C:/Users/tachi/Documents/programmi/bin/jdtls.bat
    @echo off
    python3 "C:\Users\tachi\Documents\programmi\jdtls\bin\jdtls" %*

    $ jdtls --help | head -n1
    usage: jdtls [-h] [--validate-java-version] [--no-validate-java-version]

**Comment by yegappan** [comment]
Can you include the code that registers this server with the LSP plugin?  What parameters are you passing to the LspAddServer() call?

**Comment by yegappan** [comment]
The plugin tries to directly start the specified LSP server program.  As this is a batch file, you most probably need to use `cmd /c` to execute the batch file.

**Comment by Tachi107** [comment]
> Can you include the code that registers this server with the LSP plugin? What parameters are you passing to the LspAddServer() call?

You can find the full vimrc at [~tachi/dotfiles](https://git.sr.ht/~tachi/dotfiles/tree/main/item/.vim/vimrc), but these should be the relevant bits.

```vim
if executable('jdtls')
	lspServers->add({
		filetype: 'java',
		path: 'jdtls',
		debug: true
	})
endif
g:LspOptionsSet({
	noNewlineInCompletion: true,
	usePopupInCodeAction: true
})
g:LspAddServer(lspServers)
```
> The plugin tries to directly start the specified LSP server program. As this is a batch file, you most probably need to use `cmd /c` to execute the batch file.

That doesn't seem to be the issue. Trying to do the same with clangd doesn't cause any issue

    $ command -v clangd
    C:/Users/tachi/Documents/programmi/bin/clangd.bat

    $ command -v clangd | xargs cat
    @echo off
    "C:\Users\tachi\clangd.exe" %*

**Comment by Tachi107** [comment]
Turns out there are multiple issues, but none are directly related to this plugin. Still, I'm writing theme here just in case somebody encounters the same issues:

- Yes, you were right. You cannot put .bat scripts as the `path` argument; the file must be an executable. I don't know why my clangd test worked before, but I can confirm that it doesn't work now.
- On Windows, running `python3 jdtls` forks the language server in the background, since Windows lacks a true `execve()` system call. The upstream jdtls.py wrapper launcher calls `os.execvp()` to launch the language server, and while this works on Unix-like OSes it doesn't on Windows - its [`_execvp()`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/exec-wexec-functions) function is just a wrapper around `CreateProcess()`, similar to `posix_spawn()`. I'll report this upstream as soon as possible.

The only solution I could find was extracting all the command line arguments from the jdtls.py wrapper script and set them as the `path` and `args` arguments of `LspAddServer`.

```
lspServers->add({
	filetype: 'java',
	path: 'java',
	args: ['-Declipse.application=org.eclipse.jdt.ls.core.id1', '-Dosgi.bundles.defaultStartLevel=4', '-Declipse.product=org.eclipse.jdt.ls.core.product', '-Dosgi.checkConfiguration=true', '-Dosgi.sharedConfiguration.area=C:\\Users\\tachi\\Documents\\programmi\\jdtls\\config_win', '-Dosgi.sharedConfiguration.area.readOnly=true', '-Dosgi.configuration.cascaded=true', '-Xms1G', '--add-modules=ALL-SYSTEM', '--add-opens', 'java.base/java.util=ALL-UNNAMED', '--add-opens', 'java.base/java.lang=ALL-UNNAMED', '-jar', 'C:\\Users\\tachi\\Documents\\programmi\\jdtls\\plugins\\org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar', '-data', 'C:\\Users\\tachi\\AppData\\Local\\Temp\\jdtls-6577a689d38cf4eb6f3b1b0a9ab5863258a9a0b5']
})
```

Feel free to put this info in the wiki page, and thank you and all the contributors for this awesome plugin!
