### ISSUE TITLE
 html and css language servers completion dont work without vim-vsnip and vim-snip-integ

### ISSUE THREAD

**Issue by maximyurevich** [yegappan/lsp#286]
html and css ls dont work without vsnip and vsnip-integ with vim-plug plugin manager

**Comment by andlrc** [comment]
Yes, as we discussed here https://github.com/yegappan/lsp/issues/219 it's something that needs to be addressed by the respective LSP servers. It's also documented here https://github.com/yegappan/lsp/wiki#html-language-server

**Comment by yegappan** [comment]
This is an issue with the HTML/CSS language server.  This server enables completion only when the snippetSupport is enabled:

https://github.com/vscode-langservers/vscode-html-languageserver/blob/18bed63e90d661407306d3b66a856e951036567d/src/htmlServerMain.ts#L125

This is not an issue with the LSP plugin.
