### ISSUE TITLE
Error: request initialize failed (Request initialize failed with message: Cannot read properties of undefined (reading 'petiteVue'), code = -32603)

### ISSUE THREAD

**Issue by DanielViberg** [yegappan/lsp#287]
Trying to use volar-server: 
#{                                                                                          
   \   name: 'vuels',                                                                            
  \   filetype: ['vue'],                                                                        
  \   path: '../volar-server',     
  \   args: ['--stdio'],                                                                        
  \ },

**Comment by DanielViberg** [comment]
Verified to not work with https://github.com/normen/vim-lsp-settings-adapter, if any settings might differ between for vim-lsp and this client.

**Comment by andlrc** [comment]
What is `vuels` and how can it be installed? And do they have an online repository that tracks their code?

**Comment by andlrc** [comment]
> Here is the repo: https://github.com/vuejs/language-tools

How is it installed? `npm install vuejs-lsp`?

**Comment by DanielViberg** [comment]
Using https://github.com/mattn/vim-lsp-settings and https://github.com/normen/vim-lsp-settings-adapter
Run:
:LspManageServer
Select volar-server

**Comment by andlrc** [comment]
You can also try out #290 and see if it solves your problem.

**Comment by DanielViberg** [comment]
I can confirm that the error message in this ticket has been resolved. But i'm not observing any completions, may i get your config?

Should maybe start new ticket.

**Comment by DanielViberg** [comment]
` 10 04/27/23 11:21:20: Received {'id': 21, 'jsonrpc': '2.0', 'result': {'isIncomplete': false, 'items': []}}
  9 04/27/23 11:21:20: Sent {'method': 'textDocument/completion', 'params': {'context': {'triggerCharacter': '', 'triggerKind': 1}, 'textDocument': {'uri': 'file:///home/daniel/repos/expandra/expandra-e2/resources/js/Pages/Font/Index.vue'}, 'position': {'character': 6, 'line': 28}}}
  8 04/27/23 11:21:20: Received {'id': 22, 'jsonrpc': '2.0', 'result': {'isIncomplete': false, 'items': []}}
  7 04/27/23 11:21:20: Sent {'method': 'textDocument/completion', 'params': {'context': {'triggerCharacter': '', 'triggerKind': 1}, 'textDocument': {'uri': 'file:///home/daniel/repos/expandra/expandra-e2/resources/js/Pages/Font/Index.vue'}, 'position': {'character': 7, 'line': 28}}}
  6 04/27/23 11:21:20: Received {'id': 23, 'jsonrpc': '2.0', 'result': {'isIncomplete': false, 'items': []}}
  5 04/27/23 11:21:20: Received {'method': 'textDocument/publishDiagnostics', 'jsonrpc': '2.0', 'params': {'uri': 'file:///home/daniel/repos/expandra/expandra-e2/resources/js/Pages/Font/Index.vue', 'diagnostics': [], 'version': 35}}
  4 04/27/23 11:21:21: Sent {'method': 'textDocument/documentHighlight', 'params': {'textDocument': {'uri': 'file:///home/daniel/repos/expandra/expandra-e2/resources/js/Pages/Font/Index.vue'}, 'position': {'character': 6, 'line': 28}}}
  3 04/27/23 11:21:21: Received {'id': 24, 'jsonrpc': '2.0', 'result': null}                            
  2 04/27/23 11:21:21: Sent {'method': 'textDocument/documentHighlight', 'params': {'textDocument': {'uri': 'file:///home/daniel/repos/expandra/expandra-e2/resources/js/Pages/Font/Index.vue'}, 'position': {'character': 2, 'line': 28}}}
  1 04/27/23 11:21:21: Received {'id': 25, 'jsonrpc': '2.0', 'result': null}                            
37  04/27/23 11:21:21: Received {'method': 'textDocument/publishDiagnostics', 'jsonrpc': '2.0', 'params': {'uri': 'file:///home/daniel/repos/expandra/expandra-e2/resources/js/Pages/Font/Index.vue', 'diagnostics': [], 'version': 36}}
`
Seems like result: null or items: []
