### ISSUE TITLE
Property type LspDiagVirtualText does not exist

### ISSUE THREAD

**Issue by lyncir** [yegappan/lsp#288]
Hello,

config:
```
let lspOpts = {'showDiagWithVirtualText': v:true}
autocmd VimEnter * call LspOptionsSet(lspOpts)
```
Then open file.
```
Error detected while processing function <SNR>29_Output_cb[3]..lsp#handlers#ProcessMessages[32]..lsp#handlers#ProcessNotif[29]..<SNR>30_ProcessDiagNotif[1]..lsp#diag#DiagNotification[59]..lsp#diag#ProcessNewDiags[21]..<SNR>32_DiagsRefresh[3]..<SNR>32_RemoveDiagVisualsForBuffer:
line    6
:E971: Property type LspDiagVirtualText does not exist
```

code commit: 96df7372d8066dab6096b44f9fa6238b8401bf3c

Best regards,
lyncir

**Comment by yegappan** [comment]
How are you loading the LSP plugin? Are you using a plugin manage to load the plugin?
How are you registering the language servers?  Are you using the VimEnter autocmd to register the LSP server also?

It looks like you are setting the `showDiagWithVirtualText` option after loading the plugin.

**Comment by andlrc** [comment]
I think we should consider removing the lspOptions.whatever guards in the InitOnce functions, as it will give you more possibilities to toggle options later on, such as this one.

I created t PR to remove the if statements #289 289
