### ISSUE TITLE
volar-server result: null or [{}]

### ISSUE THREAD

**Issue by DanielViberg** [yegappan/lsp#291]
Using https://github.com/vuejs/language-tools, configured thru https://github.com/mattn/vim-lsp-settings and proxied using https://github.com/normen/vim-lsp-settings-adapter, the completion results are empy.

I've attached a typical debug message for a .vue editing session.
[test.txt](https://github.com/yegappan/lsp/files/11344417/test.txt)

**Comment by DanielViberg** [comment]
[vim-lsp](https://github.com/prabirshrestha/vim-lsp) debug message.

[test.txt](https://github.com/yegappan/lsp/files/11344726/test.txt)

**Comment by andlrc** [comment]
Do you have any errors in `:LspServer debug errors` if you enable debugging with `:h lsp-cfg-debug`?

**Comment by DanielViberg** [comment]
No errors that i can see.

**Comment by DanielViberg** [comment]
Solved by the following config: 
'
let lspServers = [#{
  \	 name: 'volar-server',
  \	 filetype: ['vue', 'typescript'],
  \	 path: '<dir to server>',
  \	 args: ['--stdio'],
  \  initializationOptions: {
  \    'typescript': {
  \       'tsdk': '<dir to typescript lib>',                                                                                  
  \      },
  \    'textDocumnetSync': 2
  \    },
  \   }
  \  ]

autocmd VimEnter * call LspAddServer(lspServers)
'
Please add to wiki.

**Comment by andlrc** [comment]
Awesome, congrats on solving your problem. I think that it makes sense to add this information to the wiki.

**Comment by yegappan** [comment]
I have updated the [Wiki](https://github.com/yegappan/lsp/wiki) with information about the Volar language server.  Let me know, if any changes are needed.
