### ISSUE TITLE
Unused code in 'lspserver.vim' 

### ISSUE THREAD

**Issue by berggeist** [yegappan/lsp#292]
In the following code snippet there are two new variables introduced `heading` and `underlines`, but both are currently not used:

https://github.com/yegappan/lsp/blob/4c22665b504c14c4b01336f70d7113f5b44d3dbc/autoload/lsp/lspserver.vim#L1458-L1464

There seem to be two alternatives to solve this:

1. remove the unused code
2. make use of this variables like e.g. in this snippet:

https://github.com/yegappan/lsp/blob/4c22665b504c14c4b01336f70d7113f5b44d3dbc/autoload/lsp/lspserver.vim#L1428-L1431

If you give me a hint to the intended direction, I might prepare a PR.

**Comment by andlrc** [comment]
I think for the sake of completeness the heading and underline should be prepended to the output.

**Comment by berggeist** [comment]
@andlrc  thanks for your reply. I've created a PR. let's wait for @yegappan 's final decision.

**Comment by yegappan** [comment]
I have merged the PR.
