### ISSUE TITLE
How to hide "Error: Unsupported notification message" for jdtls

### ISSUE THREAD

**Issue by maximyurevich** [yegappan/lsp#294]

**Comment by yegappan** [comment]
Can you include the complete error message (including the notification message)?

**Comment by maximyurevich** [comment]
> Can you include the complete error message (including the notification message)?

Error: Unsupported request message received from the LSP server (jdtls), message = {'id': '2', 'jsonrpc': '2.0', 'method': 'workspace/executeClientCommand', 'params': {'arguments': [], 'command': '_java.reloadBundles.command'}}

**Comment by andlrc** [comment]
I'm confused as to if this is related to notifications or request replies in general? As the issue titles mentions notifications, while the copied error is related to the later.

**Comment by andlrc** [comment]
FWIW then you can "silence" notifications by `:h lsp-cfg-customNotificationHandlers`.

**Comment by Tachi107** [comment]
This might be somewhat related to https://github.com/yegappan/lsp/issues/125

**Comment by girishji** [comment]
Should be fixed by #309
