### ISSUE TITLE
Enable documentation previews with omnicompletion?

### ISSUE THREAD

**Issue by newtonne** [yegappan/lsp#304]
Is there a way to enable documentation previews with omnicompletion?

I prefer to explicitly trigger autocompletion so I have set `autoComplete: false` and I'm using omnicompletion, however, the documentation previews don't seem to be available.

**Comment by andlrc** [comment]
If you use a LSP that supports `completionLazyDoc` then you'll need to move around some of the code blocks, I assume. I havn't found any server that supports this though? 🤔

**Comment by newtonne** [comment]
Thanks. I'll try and take a look at this at some point this week.

**Comment by yegappan** [comment]
@andlrc: The Python pyright language server supports lazy resolving the documentation details for a completion item.

**Comment by yegappan** [comment]
I have merged PR #320.  Can you try using the latest version of the plugin and see whether it resolves this issue?

**Comment by newtonne** [comment]
Yup, this looks good. Thanks a lot 👍 

One question, any idea how I can get rid of the weird border around the popup window?

**Comment by lithammer** [comment]
> One question, any idea how I can get rid of the weird border around the popup window?

```vim
set completepopup+=border:off
```

**Comment by newtonne** [comment]
Brilliant. Thanks!
