### ISSUE TITLE
Is there a builtin function that return the number of errors and warnings?

### ISSUE THREAD

**Issue by ubaldot** [yegappan/lsp#308]
...or one should write his own function to count the number of warnings and errors in the location list?

**Comment by andlrc** [comment]
There is such a function, it's described in "7. Diagnostics"

> The function lsp#lsp#ErrorCount() function can be used to get the count of the
diagnostic messages in the current buffer by type.  This function returns a
Dictionary with the following keys: Info, Hint, Warn and Error.  The value for
these keys is the number of diagnostic messages of the corresponding type.
This function can be used to display the number of diagnostics in the current
buffer in a 'statusline'.

**Comment by ubaldot** [comment]
Follow up question: how often the loc list is updated? I am asking because I was thinking to call such a function in an autocmd triggered by CursorHold event and I don’t want to set a timeout which is “compliant” with the update rate of the loc list. :)

**Comment by andlrc** [comment]
> Follow up question: how often the loc list is updated?

It's hard to tell, as the language server owns the diagnostics, and therefore decides when to notify the client with new diagnostics.

For instance the typescript-language-server will report diagnostics for file A when A is edited, but might also report diagnostics for A when B is edited, if a depends on B.

**Comment by ubaldot** [comment]
Thank you!

I think I get everything working by now, but I need a small hint for improvement if you have some time. 
At the moment I have the following: 

```
augroup UpdateDiag
    autocmd!
    autocmd BufEnter *  b:num_warnings = 0 | b:num_errors = 0
    autocmd CursorHold,CursorHoldI * b:num_warnings = lsp#lsp#ErrorCount()['Warn']
                \ | b:num_errors = lsp#lsp#ErrorCount()['Error']
augroup END
```

and it works OK, but I wish to use  such a `LspDiagsUpdated` event instead of `CursorHold,CursorHoldI ` but I am failing in doing it :(

**Comment by andlrc** [comment]
What did you try?

    autocmd CursorHold,CursorHoldI *

Should be

    autocmd User LspDiagsUpdated

**Comment by ubaldot** [comment]
I was doing something very stupid: 

`autocmd LspDiagsUpdated *`

:-/
