### ISSUE TITLE
Dart language server

### ISSUE THREAD

**Issue by guildem** [yegappan/lsp#313]
Adding Dart language server into the wiki could be a nice add-on.

Something like this : 

```markdown
# Rust-analyzer

**Language**: Dart

**Home Page**: https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/tool/lsp_spec/README.md

Sample code to add the dart language server to the LSP plugin:

\```
call LspAddServer([#{name: 'dart',
                 \   filetype: ['dart'],
                 \   path: 'dart',
                 \   args: ['language-server', '--client-id', 'vim']
                 \ }])
\```
```

**Comment by Shane-XB-Qian** [comment]
you verified this worked, right?

// the `path` should be an absolute path to compliance most user cases.

**Comment by guildem** [comment]
I used it this week, it works.

Not sure about the absolute path. On debian it should be `/usr/lib/dart/bin/dart`. I use archlinux, and I can install dart with pacman and find it on `/opt/dart-sdk/bin/dart`, or use Android Studio (Flutter) installing it elsewhere, or like I do (recommended), install the flutter sdk and dart only for my user, configuring PATH with the folder I put it. You can also see these two links managing different installations : 
- https://dart.dev/get-dart
- https://docs.flutter.dev/get-started/install/linux (flutter uses dart)

Finally, running `$ dart` will work. Path could even be optional, main path being the server executable name called directly from PATH, for usability (unless adding 2 times the same server is a common thing). This reduces and simplifies the LspAddServer line for 99% of use cases and keeps an option for special cases.

**Comment by Shane-XB-Qian** [comment]
thx, yegappan should would update this to wiki some days later.

// just someone may did not install it into $PATH, so the example better be an absolute path.

**Comment by guildem** [comment]
I don't disagree to use an absolute path into the wiki, but be aware multiple use cases and absolute paths are possible with dart/flutter (more than most other languages), so maybe a template path `[PATH_TO]/dart` or debian path + another line explaining this may change depending of user's configuration should avoid getting issues worrying about a copy/paste not working on some hosts.

**Comment by girishji** [comment]
FWIW, eclipse jdtls works as expected, in case anyone is thinking of adding these examples to the doc.

```
  {
    name: 'jdtls',
    filetype: 'java',
    path: 'jdtls', # a full path here if different versions are installed
    args: [
      "-configuration", expand("$HOME") .. "/.cache/jdtls",
      "-data", expand("$HOME") .. "/.local/share/eclipse", # this can be set per project
    ],
  },
```

**Comment by yegappan** [comment]
Thanks for the sample code to add the Dart server.  I have updated the Wiki with this information.
