### ISSUE TITLE
Missing link for |popupmenu-keys| in doc/lsp.txt

### ISSUE THREAD

**Issue by girishji** [yegappan/lsp#315]
In section **"6. Insert mode completion"** of doc/lsp.txt, the destination to link from `|popupmenu-keys|` is missing. I think the keys are Ctrl-N and Ctrl-P to select popup menu items.

One can also map `<Tab>` and `<Shift-Tab>` to select popup menu items as follows (I think this is more intuitive):

```
# When tab has only whitespace before it, insert tab; otherwise insert <C-N>
def! g:CleverTab(reverse: bool): string
  var whitespaceOnly = strpart( getline('.'), 0, col('.') - 1 ) =~ '^\s*$'
  return whitespaceOnly ? (reverse ? "\<S-Tab>" : "\<Tab>") : (reverse ? "\<C-P>" : "\<C-N>")
enddef
inoremap <Tab> <C-R>=CleverTab(v:false)<CR>
inoremap <S-Tab> <C-R>=CleverTab(v:true)<CR>
```

**Comment by andlrc** [comment]
I don't think that it's missing? see https://vimhelp.org/insert.txt.html#popupmenu-keys

**Comment by girishji** [comment]
You're right, my installation was missing a few files. Closing this.
