### ISSUE TITLE
Invasive diagnostic highlight.

### ISSUE THREAD

**Issue by ubaldot** [yegappan/lsp#317]
Is there a way to have only text and highlight of the sign next to the line number without highlighting the whole line in diagnostics, see example below? 
Having the whole line highlighted is a bit invasive for me, that underlined **E>** on the side is more than enough. :)

![image](https://github.com/yegappan/lsp/assets/10845685/b989922f-2772-483b-b4f6-80e69f42b596)

**Comment by berggeist** [comment]
The highlight group ```LspDiagLine``` controls the colors for those lines. It's also described in the help for the lsp plugin.
Simply setting ```LspDiagLine``` to ```NONE``` like ```hi link LspDiagLine NONE``` should be enough.

**Comment by andlrc** [comment]
If you want diagnostics to be highlighted in the line then there is an option for that.

If you want diagnostics to be shown as virtual text then there is also an option for that.
