### ISSUE TITLE
Please add this to the wiki page

### ISSUE THREAD

**Issue by girishji** [yegappan/lsp#323]
Eclipse jdtls needs some extra configuration that is quite useful.

The completion list get polluted with suggestions from `sun.*`, `javax.awt.*`, etc. They can to be filtered out like this:

```
    initializationOptions: {
      settings: {
        java: {
          completion: {
            filteredTypes: [ "com.sun.*", "java.awt.*", "jdk.*", "org.graalvm.*", "sun.*", "javax.awt.*", "javax.swing.*" ],
          },
        },
      },
    },
```
More information here: https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request

Also, add a note in the documentation that wiki page has more details about server configuration.

**Comment by yegappan** [comment]
Thanks for providing the details.  I have updated the wiki page with these instructions.

**Comment by Shane-XB-Qian** [comment]
> filtered out

@girishji 
um.. a bit confused or curious to ask: you are trying to filter 'out', or getting those?
seems awt, swing etc maybe useful still, right?

**Comment by Shane-XB-Qian** [comment]
@yegappan perhaps the wiki should notice that 'filter out' just an example, but not a must necessary or good practice to filter out those packages, or would be thought as those are our recommend which maybe mis-understanding sth.

**Comment by yegappan** [comment]
@Shane-XB-Qian I have updated the wiki to mention this.
