### ISSUE TITLE
Dart: Unsuported notification received from LSP server

### ISSUE THREAD

**Issue by guildem** [yegappan/lsp#324]
When opening or updating a dart file, dart language server send those :

```
Error: Unsupported notification received from LSP server {'method': '$/analyzerStatus', 'jsonrpc': '2.0', 'params': {'isAnalyzing': true}}
Error: Unsupported notification received from LSP server {'method': '$/analyzerStatus', 'jsonrpc': '2.0', 'params': {'isAnalyzing': false}}
```

Those seems to have no effect on the global behavior, only showing on status line. Is those known messages of the LSP ? If not, is there a way to ignore them ?

**Comment by yegappan** [comment]
I have committed 132cf62fc72703b8d8622448fdca308cbc0950b3 to ignore this notification message.
