### ISSUE TITLE
Add support for UTF-16 offsets

### ISSUE THREAD

**Issue by andlrc** [yegappan/lsp#327]
Now that vim got a lot of utility functions to count length in UTF-16 I think it would make sense to use these if possible, as UTF-16 offsets is the default for language servers. https://github.com/vim/vim/commit/67672ef097dd708244ff042a8364994da2b91e75

```
		/**
		 * The position encodings supported by the client. Client and server
		 * have to agree on the same position encoding to ensure that offsets
		 * (e.g. character position in a line) are interpreted the same on both
		 * side.
		 *
		 * To keep the protocol backwards compatible the following applies: if
		 * the value 'utf-16' is missing from the array of position encodings
		 * servers can assume that the client supports UTF-16. UTF-16 is
		 * therefore a mandatory encoding.
		 *
		 * If omitted it defaults to ['utf-16'].
		 *
		 * Implementation considerations: since the conversion from one encoding
		 * into another requires the content of the file / line the conversion
		 * is best done where the file is read which is usually on the server
		 * side.
		 *
		 * @since 3.17.0
		 */
		positionEncodings?: [PositionEncodingKind](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#positionEncodingKind)[];
```

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#clientCapabilities

See https://github.com/yegappan/lsp/pull/197 for why we currently only "really" supports utf-32 offsets.

**Comment by yegappan** [comment]
I have committed the support for the UTF-8 and UTF-16 position offsets in 11dabbb9fef88760c3b160e905db1ae6b0bef1c6.  Please try it out and let me know if you see any issues.
