### ISSUE TITLE
Error detected while processing function

### ISSUE THREAD

**Issue by DanielViberg** [yegappan/lsp#339]
Error detected while processing function <SNR>71_Output_cb[3]..lsp#handlers#ProcessMessages[32]..lsp#handlers#ProcessNotif[32]..<SNR>72_ProcessDiagNotif[1]..lsp#diag#DiagNotification[64]..lsp#diag#Pro
cessNewDiags[21]..<SNR>74_DiagsRefresh[1]..BufWinEnter Autocommands for "*"..function <SNR>53_Highlight_Matching_Pair:
line  149:
E801: ID already taken: 3

Arises randomly during opening files.

**Comment by yegappan** [comment]
The Highlight_Matching_Pair() function is defined in the matchparen plugin.  The LSP plugin doesn't use the match ID 3.  It looks like when the LSP plugin loads a buffer using bufload(), it somehow leads the matchparen plugin to add the match with the ID 3 again leading to this error.  Is there a list of steps/configuration that you use when you see this error?

**Comment by Shane-XB-Qian** [comment]
@yegappan maybe the modlines, specially some files had some chars looked like modlines (but actually it is not)
then err or unexpected cases happened...
so maybe should avoid modlines when bufload(), but:
1, not sure how or is it ok?
2, i think silent! was not an ok solution for it.

**Comment by Shane-XB-Qian** [comment]
but even no lsp, that file may have err/unexpected cases still when directly open it, so not sure if worthy to fix it.

**Comment by yegappan** [comment]
I have committed d7d29b63960f4f591068f6f67230c9e8740e053c to silence the error messages when loading a buffer.  Does this commit fix this issue?

**Comment by DanielViberg** [comment]
This seems to be solved
