### ISSUE TITLE
arduino-language-server exited with status 2: how to debug?

### ISSUE THREAD

**Issue by ubaldot** [yegappan/lsp#341]
I have installed this LSP:

https://github.com/arduino/arduino-language-server

and I tested it from command line with:

`./arduino-language-server -cli-config /Users/ubaldot/Library/Arduino15/arduino-cli.yaml -cli /opt/homebrew/bin/arduino-cli -fqbn arduino:avr:uno`

and the LSP appear to work. 
However, when I try to use it in Vim I got a `arduino-language-server exited with status 2` and I don't know how to debug it. 
This is what I how I registered it:

```
    {
        name: 'arduino-language-server',
        filetype: ['arduino'],
        path: $HOME .. '/Documents/arduino-language-server/arduino-language-server',
        args: ['-clangd /usr/bin/clangd',
                '-cli-config /Users/ubaldot/Library/Arduino15/arduino-cli.yaml',
                '-cli /opt/homebrew/bin/arduino-cli',
                '-fqbn arduino:avr:uno']
    }

```
`ft 'arduino'` is defined through this plugin that I have installed: https://github.com/stevearc/vim-arduino.
`:LspServer show status` say that the LSP is running.

Any hints?

**Comment by yegappan** [comment]
How did you solve this issue?

**Comment by ubaldot** [comment]
It is not solved but I am suspicious that the problem is on the LS side and I opened an issue there after I have noticed a weird `Version 0.0.0` : https://github.com/arduino/arduino-language-server/issues/160

I also figured in their issue log that there are many having issue with NeoVim and I read in [one](https://github.com/arduino/arduino-language-server/issues/155) comment that: 

`arduino-language-server does not support lsp semantic tokens and NvChad tries to set it.`

Which I have no idea what does it mean as I am a _user_ but it may relates to your lsp. 

Needless to say that if it gets solved I will let you know so we can enrich the Wiki of this VERY WELL DONE lsp client! :)

**Comment by ubaldot** [comment]
Update: I managed to install a released version of the LSP but still I have `exit with status 2`. Can that be because arduino-language-server _does not support lsp semantic tokens_?

**Comment by yegappan** [comment]
Can you add `debug: true` when registering the LSP server?  You can then use the `:LspServer debug errors` command to
display the messages emitted by the language server in stderr.  This most probably will help you to find the reason for
the LSP server exiting with status 2.

The support for semantic tokens is not related to this.

**Comment by ubaldot** [comment]
Thanks! FYI: https://github.com/arduino/arduino-language-server/issues/162 I tried to google the error by myself and it seems golang related, so I opened an issue there.

**Comment by yegappan** [comment]
Can you try using the following args when registering the language server:
```
    args: ['-clangd', '/usr/bin/clangd',
           '-cli-config', '/Users/ubaldot/Library/Arduino15/arduino-cli.yaml',
           '-cli', '/opt/homebrew/bin/arduino-cli',
           '-fqbn', 'arduino:avr:uno']
```

Each space separated command-line argument should be supplied as a separate List item to `args`.

**Comment by ubaldot** [comment]
It went through! Thanks! I am making further tests now but I can already provide some progress (before the capabilities list was empty)
```

'/Users/ubaldot/Documents/arduino-language-server/arduino-language-server' Language Server Capabilities
=======================================================================================================
codeActionProvider: {'codeActionKinds': ['quickfix', 'refactor', 'info']}
completionProvider: {'allCommitCharacters': [' ', '	', '(', ')', '[', ']', '{', '}', '<', '>', ':', ';', ',', '+', '-', '/', '*', '%', '^', '&', '#', '?', '.', '=', '"', '''', '|'], 'completionItem': {}, 'triggerCharacters': ['.', '<', '>', ':', '"', '/']}
definitionProvider: {}
documentFormattingProvider: {}
documentHighlightProvider: {}
documentOnTypeFormattingProvider: {'firstTriggerCharacter': ''}
documentRangeFormattingProvider: {}
documentSymbolProvider: {}
executeCommandProvider: {'commands': ['clangd.applyFix', 'clangd.applyTweak']}
hoverProvider: {}
renameProvider: {}
signatureHelpProvider: {'triggerCharacters': ['(', ',']}
textDocumentSync: {'save': {'includeText': true}, 'change': 2, 'openClose': true}
workspaceSymbolProvider: {}
~additionalInitResult_serverInfo: {'version': '0.7.4', 'name': 'arduino-language-server'}
```
