### ISSUE TITLE
Omnisharp doesn't seem to work.

### ISSUE THREAD

**Issue by DesantBucie** [yegappan/lsp#342]
I've installed Omnisharp via nix:
```vim
var lspServers = [
    {
     name: 'omnisharp',
     filetype: ['cs'],
     path: '/nix/store/j0nqxirnmp86ibcj674r3r0rirwwfb4b-omnisharp-roslyn-1.39.6/bin/OmniSharp',
     args: ['--z', '--languageserver', '--encoding', 'utf-8']
    },
    {
     name: 'clangd',
     filetype: ['c', 'cpp'],
     path: '/usr/bin/clangd',
     args: ['--background-index']
    }
]
g:LspAddServer(lspServers)
```

when opening dotnet console project nothing happens, LspShowAllServers shows that the server is running.
```
Filetype: 'cs'
Server Name: 'omnisharp'
Server Path: '/nix/store/j0nqxirnmp86ibcj674r3r0rirwwfb4b-omnisharp-roslyn-1.39.6/bin/OmniSharp'
Status: Running
```

Do I have to configure something additionally?

**Comment by DesantBucie** [comment]
...Easily Fixed. You have typo in wiki. If I put `-z` instead of `--z` the thing starts to work :). Also I could figure it myself, but those small errors are hard to find, aren't they?

**Comment by Shane-XB-Qian** [comment]
last update of wiki was 2 weeks ago, i saw it is `--z`
anyway, if it works for you now, please close then, or you'd like to share some specific c# configure, then please feedback.

**Comment by DesantBucie** [comment]
Yes, sorry I forgot to close.
