### ISSUE TITLE
terrible performance of decodeLocation in symbol search

### ISSUE THREAD

**Issue by Shane-XB-Qian** [yegappan/lsp#344]
```vim
   symInfo->map((_, sym) => {
       if sym->has_key('location')
	 lspserver.decodeLocation(sym.location)
       endif
       return sym
     })
```

i may suggest giving up decodeLocation here, otherwise here looks benefit less than profit.

**Comment by yegappan** [comment]
I have committed 5def4b894e2de66de902d7f3ccbffac4a26048b7 to decode the symbol location only when needed.  This should help.

When did you see the poor performance of decoding the symbol location?  Do you have a test file that shows the performance drop?

Note that if the symbol location is not decoded, then the plugin cannot properly handle symbols in lines with multibyte and combined characters.

**Comment by Shane-XB-Qian** [comment]
> to decode the symbol location only when needed. This should help.

seems no

> Note that if the symbol location is not decoded, then the plugin cannot properly handle symbols in lines with multibyte and combined characters.

yes, i know, but i am not sure if it had higher benefit than the cost.


> When did you see the poor performance of decoding the symbol location?

when symbol search something, i am testing in a golang proj.
but you can image: it would parse huge size of bufs to re-calc the loc/range in this place, and kicked off something else.

**Comment by yegappan** [comment]
I have committed d7d29b63960f4f591068f6f67230c9e8740e053c to silence the messages displayed when loading new buffers.  Can you see whether this commit helps?

**Comment by Shane-XB-Qian** [comment]
> silence the messages displayed when loading new buffers. Can you see whether this commit helps?

no, it does not, the problem key is it reads lots bufs to re-calc and etc.

and i think `silence` here is a bad idea, (maybe i would suggest you rollback this commit), since it maybe hide err but maybe worthy to notice.

**Comment by Shane-XB-Qian** [comment]
or whatever, since you added `silent` for that, then #339 perhaps can be closed.

**Comment by yegappan** [comment]
I have committed 67c30fbab8ac0095de74508c729d115b6f334318 to force the use of a particular offset encoding with a language server.  Can you try setting this to 'utf-32' when registering the 'gopls' language server?

**Comment by Shane-XB-Qian** [comment]
> I have committed [67c30fb](https://github.com/yegappan/lsp/commit/67c30fbab8ac0095de74508c729d115b6f334318) to force the use of a particular offset encoding with a language server. Can you try setting this to 'utf-32'

yes, but it meant all decode of range/loc were give up, i was just suggesting giving up symbol search.
// but to be simple, i think it's ok.
