### ISSUE TITLE
Autocommand of `lsp.AddFile` too early for filetype detection

### ISSUE THREAD

**Issue by kikniknik** [yegappan/lsp#348]
I have configured rust-analyzer lsp server as shown in README, but when I edit `main.rs` or any other rust file, the buffer isn't registered to lsp. `:LspShowAllServers` output is:
```
Filetype Information
====================
Filetype: 'rust'
Server Name: 'rustls'
Server Path: '/usr/bin/rust-analyzer'
Status: Not running

Buffer Information
==================
```

I've noticed that `lsp.AddFile` is called in an `autocmd` for `BufNewFile,BufReadPost` events, and `bnr->getbufvar('&filetype')` inside `lsp.AddFile` returns an empty string whenever it's called from that autocmd. Instead, if I call it manually, filetype exists and the buffer is registered succesfully.

That autocmd is executed before filetype detection. Output of `:9verbose edit src/main` has
```
Executing BufRead Autocommands for "*"
autocommand lsp.AddFile(expand('<abuf>')->str2nr())
```
before
```
Executing BufRead Autocommands for "*.rs"
autocommand setf rust
```

If instead of `BufNewFile,BufReadPost` events, a `FileType` event is used, then buffers are registered successfully by that autocmd.

**Comment by yegappan** [comment]
Thanks for the suggestion to use the FileType autocmd. I have committed 0b67f2ff8ad371a66a11754c6a2ed24c808e64e4 to also use the FileType autocmd to start the LSP server.  Let me know if this addresses this issue.

**Comment by kikniknik** [comment]
Yes the commit fixes it, thanks!
