### ISSUE TITLE
autocompletion as separate plugin

### ISSUE THREAD

**Issue by dacyberduck** [yegappan/lsp#349]
just a suggestion to make the completion a different plugin so that snippet and other completion can be used even if the lsp is not running

**Comment by maximyurevich** [comment]
No, please, for what? Asynccomplete and ddc are weak and slow compared to this plugin.

**Comment by maximyurevich** [comment]
This plugin is a good monolith

**Comment by yegappan** [comment]
Insert-mode completion is one of the core LSP functionality.  Splitting that into a separate plugin from this plugin, will not
make it convenient for a end user to use this plugin.  Also, the current completion functionality is tightly coupled with
the completion information returned by a language server (according to the LSP specification) and will not be useful
in other contexts.
