### ISSUE TITLE
Flickering while cycling through insert-completion popup menu

### ISSUE THREAD

**Issue by kikniknik** [yegappan/lsp#352]
I've noticed a flickering when browsing the completion popup menu. It seems that an entire redraw is done whenever the selection changes. It is seen clearly if `writedelay=1` is set. 

After a bit of searching I've discovered that the thing that triggers the redraw is setting popup filetype to 'lspgfm' at `CompleteChanged` event. Specifically, setting `encoding=utf-8` inside `lspgfm.vim`. Is there a need to set it every time? Isn't it a global-only option?

**Comment by yegappan** [comment]
Thanks for reporting the issue and finding the root cause.  I have committed 3dee86b2790634b0f5210f622e7bdd68e06a8ff6 to fix this issue.
