### ISSUE TITLE
Allow to change showInlayHints during runtime

### ISSUE THREAD

**Issue by vimpostor** [yegappan/lsp#356]
It would be helpful if one could toggle `showInlayHints` during runtime, as I don't want to see inlay hints all the time due to the clutter, but sometimes they are helpful.

In VSCode there even is an extra shortcut, where you can hold Ctrl+Alt to temporarily show inlay hints.

Is there some way to make this work with this plugin? If I don't enable them before starting the LSP server, then they will never show, i.e. even calling the following function during runtime will not make them show up:
```vim
:call LspOptionsSet(#{showInlayHints: 1})
```

It would be nice if this plugin could toggle them, if I set the option during runtime.

**Comment by Shane-XB-Qian** [comment]
that may depend on lsp server, e.g rust analyser, it would not init give inlay hints.
// or it was a its bug? or it just did like your demand.

**Comment by yegappan** [comment]
I have committed e5b32d6549c43e0dfa777b5a2ddb288e612e78a3 to add support for enabling/disabling inlay hints.  Can you try the latest plugin?  The command `:LspInlayHints enable` enables inlay hints and the command `:LspInlayHints disable` disables inlay hints for the current Vim session.  You can also use the `showInlayHints` option to enable or disable inlay hints across Vim sessions.

**Comment by Shane-XB-Qian** [comment]
seems good, thanks.
// a little different is clangd maybe/canbe init enabled by default, but rust would/can not.
// but so far, that's a knew issue, or rust-analyser's feat, maybe.

**Comment by vimpostor** [comment]
Thanks it works perfectly.

**Comment by Shane-XB-Qian** [comment]
> // a little different is clangd maybe/canbe init enabled by default, but rust would/can not.
> // but so far, that's a knew issue, or rust-analyser's feat, maybe.

@yegappan i opened PR #357 trying to correct it.
