### ISSUE TITLE
insert mode '(' overwrites auto-pairs mapping

### ISSUE THREAD

**Issue by dacyberduck** [yegappan/lsp#364]
In insert mode '(' & '{' keys are mapped to show lsp signature which overwrites mappings from auto pairs plugin. How do I solve this?

**Comment by yegappan** [comment]
You can try disabling the show signature feature for all the language servers by setting the 'showSignature' option to v:false in your .vimrc file:

```
  call LspOptionsSet({'showSignature': v:false})
```

I have also committed 40645ca294540792504ce3db4cdf84ee45868396 to not map the trigger characters when the show signature feature is disabled for a language server.  For example, to disable the show signature feature for the clangd language server, you can use the following when registering the language server:

```
  call LspAddServer([#{name: 'clangd',
                   \   filetype: ['c', 'cpp'],
                   \   path: exepath('clangd-15'),
                   \   args: ['--background-index', '--clang-tidy'],
                   \     features: #{
                   \             signatureHelp: v:false
                   \     }
                   \ }])
```

**Comment by yegappan** [comment]
Is this problem fixed?

**Comment by philFernandez** [comment]
I'm having a similar issue. @yegappan your suggestion fixed the problem with pressing ( and {, but now when I press enter after writing the header of a function the cursor does not go into the body of the function as it should. Probably has something to do with the "<CR>" mapping for completion, but I'm not sure how to overcome it. Thanks for the awesome LSP plugin!
