### ISSUE TITLE
`addiotionalTextEdits` should be in `initializationOptions`?

### ISSUE THREAD

**Issue by maximyurevich** [yegappan/lsp#376]
Hello, I have a problem with double import with pyright and golang. How to apply `addiotionalTextEdits` option?
https://github.com/yegappan/lsp/issues/259

**Comment by Shane-XB-Qian** [comment]
seems pyright did not support auto import unless pylance, how did you make it work?
anyway, history or information or description in #259 should have been answer your question in this lsp side, please donot repeatly dup open tickets.
// IMO we perhaps cannot offer tech support, specially via this way.
