### ISSUE TITLE
lsp gives error messages when no lsp should be active

### ISSUE THREAD

**Issue by MartinAskestad** [yegappan/lsp#377]
I`m running lsp for typescript for example, everything works fine. Opens a terminal with `:term` and I get the message
```Error: language server for "" file type supporting "documentHighlight" feature is not found```

But I haven't registered a lsp for blank file type, why is this error message showing?

**Comment by yegappan** [comment]
Do you have the `autoHighlight` option enabled?  I couldn't reproduce this problem after opening a terminal window. 
I think a check for a buffer with an empty filetype is missing.  Do you have a sequence of steps to reproduce this issue?

**Comment by MartinAskestad** [comment]
Ah! I discovered I have a autocmd that triggers LspHighlight, I should probably change that to use the property in lsp options. Thank you!
