### ISSUE TITLE
Diagnostics isn't updated after fix sometimes

### ISSUE THREAD

**Issue by kohnish** [yegappan/lsp#39]
I haven't found a condition when it happens but sometimes fixing the clangd(clang-tidy) warning, highlight doesn't disappear. The only way to fix it is to restart the vim completely (e! doesn't help).   
  
I'll update this issue as soon as I found the exact condition to reproduce this.

**Comment by kohnish** [comment]
`  autocmd BufWipeOut * call lsp#removeFile(expand('<abuf>')->str2nr())` might be the culprit.

**Comment by Shane-XB-Qian** [comment]
@kohnish this lsp author had push some commits perhaps fixed this yesterday, pls check..

**Comment by kohnish** [comment]
Thanks. Unfortunately I migrated to vim-lsc which seems to be more feature rich with  differential diagnostics and hierarchy tree window and etc.  
But I'll give lsp try again sometime and if I encounter this issue, I'll reopen this ticket.

**Comment by Shane-XB-Qian** [comment]
well, you can think this is lightweight and faster lsp client, 
besides you can customize some feature or local hack something by you own, that maybe some interesting thing, is'nt it?
// `rich` always meant `complex` in nowdays, haha............ so do you like simple or `rich`? :-)
