### ISSUE TITLE
Inlay hints callback corruption?

### ISSUE THREAD

**Issue by lithammer** [yegappan/lsp#395]
I've noticed a weird behaviour with the gopls language server. I can consistently reproduce it on bigger projects, where I assume the `textDocument/inlayHint` request takes a long time.

The first symptom was that the workspace never finished loading so no LSP functionality worked. But I was receiving this error:

```
Error: request textDocument/inlayHint failed (no result)
```

It seemed weird that the result would be empty, but no error from the server so I extended the error message like so:

```diff
-util.ErrMsg($'request {method} failed (no result)')
+util.ErrMsg($'request {method} failed (no result): {reply->string()}')
```

And it revealed something curious. This is the error I'm getting:

```
Error: request textDocument/inlayHint failed (no result): 
{'method': 'workspace/configuration', 'jsonrpc': '2.0', 'id': 2, 'params': {'items': [{'section': 'gopls'}]}}
```

So I'm receiving a `workspace/configuration` response in the `textDocument/inlayHint` callback??

---

```
var servers = [
  {
    name: 'gopls',
    path: 'gopls',
    args: ['serve'],
    filetype: ['go', 'gomod', 'gowork', 'gotmpl', 'gohtmltmpl', 'gotexttmpl'],
    syncInit: true,
    debug: true,
    traceLevel: 'verbose',
    rootSearch: ['go.work', 'go.mod'],
    workspaceConfig: {
      gopls: {
        analyses: {
          nilness: true,
          unusedparams: true,
          unusedwrite: true,
          useany: true,
        },
        hoverKind: 'FullDocumentation',
        linksInHover: false,
        gofumpt: true,
        completeUnimported: true,
        # semanticTokens: false,
        staticcheck: true,
        usePlaceholders: true,
        completionDocumentation: true,
        codelenses: {
          generate: true,
          test: true,
          run_vulncheck_exp: true,
        },
        hints: {
          assignVariableTypes: false,
          compositeLiteralFields: true,
          compositeLiteralTypes: false,
          constantValues: true,
          functionTypeParameters: true,
          parameterNames: true,
          rangeVariableTypes: true,
        },
      }
    }
  }
]

var opts = {
  autoComplete: true,
  autoHighlight: true,
  highlightDiagInline: true,
  showDiagOnStatusLine: true,
  showInlayHints: true,
  snippetSupport: true,
  vsnipSupport: true,
}

g:LspAddServer(servers)
g:LspOptionsSet(opts)
```

**Comment by Shane-XB-Qian** [comment]
how big what you mean? i tried 170M size prj at my laptop, occasionally looks i can repro this,
and not sure your test on reply msg, but i felt it was gopls was not "really ready" for inlay-hints.
// seems not exactly or not sure same case like rust case, but try https://github.com/yegappan/lsp/pull/357 maybe helpful.

**Comment by lithammer** [comment]
> how big what you mean? i tried 170M size prj at my laptop, occasionally looks i can repro this,

Well I can fairly consistently reproduce it on this repo: https://github.com/googleapis/google-cloud-go

> and not sure your test on reply msg, but i felt it was gopls was not "really ready" for inlay-hints.
> // seems not exactly or not sure same case like rust case, but try #357 maybe helpful.

Yeah kind of seems like we're sending `textDocument/inlayHint` too early 🤔 That fix doesn't seem to help, unfortunately.

**Comment by lithammer** [comment]
#396 doesn't really fix the problem though. I had to bump the timer to something like 15000 to get it to work.

I do wonder if this isn't a bug in Vim itself though. Specifically in `ch_sendexpr()` when you give it a `callback`. I don't really know how the LSP channel stuff works in Vim. But it seems like it's expecting a regular request → response cycle. But this doesn't work since a request can be initiated from both the client and the server at any time.

From my testing, gopls sends something like 3 `workspace/configuration` requests during startup. What ends up happening is something like this:

```
[1] Client → Server: initialize
[1] Server → Client: InitializeResult
[2] Client → Server: initialized
[3] Server → Client: workspace/configuration
[3] Client → Server: ConfigurationItem[]
[4] Client → Server: textDocument/inlayHint
[5] Server → Client: workspace/configuration
[4] Server → Client: InlayHint[]
```

Now the client is confused because it thinks `[5]` is a response to `[4]`, but it's actually a server initiated request.

So just delaying the `textDocument/inlayHint` request only makes this problem less likely to happen since server requests are quite rare after the initial startup sequence.
In fact, this could happen at any point for any request if the server decides to also send a request before responding to the client's request.

```
[1] Client request →
[2]                ← Server request (client thinks this a response)
[3]                ← Server response
```

**Comment by yegappan** [comment]
The Vim LSP channel code matches the response from the LSP server with an outstanding request by comparing the ID:

https://github.com/vim/vim/blob/master/src/channel.c#L3052

In the above example, it should match the ID in the message (4) with the outstanding request message. 

If the IDs in both the request messages sent by the server and sent by the client match, then it will lead
to a problem.  This can be fixed by changing the may_invoke_callback() function to check whether the
received message is a request or a response message.  If the "method" field is present, then it is a
request message.  Otherwise it is a response message.

**Comment by yegappan** [comment]
Can you try the following patch to Vim?

```
diff --git a/src/channel.c b/src/channel.c
index cdb956e7c..115c26b61 100644
--- a/src/channel.c
+++ b/src/channel.c
@@ -2927,9 +2927,13 @@ may_invoke_callback(channel_T *channel, ch_part_T part)
            seq_nr = 0;
            if (d != NULL)
            {
-               di = dict_find(d, (char_u *)"id", -1);
-               if (di != NULL && di->di_tv.v_type == VAR_NUMBER)
-                   seq_nr = di->di_tv.vval.v_number;
+               // ignore "id" in the LSP request messages.
+               if (!dict_has_key(d, "method"))
+               {
+                   di = dict_find(d, (char_u *)"id", -1);
+                   if (di != NULL && di->di_tv.v_type == VAR_NUMBER)
+                       seq_nr = di->di_tv.vval.v_number;
+               }
            }
 
            argv[1] = *listtv;
```

**Comment by Shane-XB-Qian** [comment]
i verified, not sure outage, but seems it helped.

**Comment by lithammer** [comment]
I also verified that the above Vim patch seems to solve the problem 👍

**Comment by lithammer** [comment]
Closing this since it's an upstream issue and there are fixes on the way.

- https://github.com/vim/vim/pull/13133
- https://github.com/vim/vim/pull/13141

**Comment by yegappan** [comment]
Can you try the latest Vim (9.0.1924 or after) and see whether this issue with gopls is fixed?

**Comment by lithammer** [comment]
Unfortunately, this still happens on 9.0.1927:

```
:version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 21 2023 14:57:42)
Included patches: 1-1927
```

```
Error: request textDocument/inlayHint failed (no result):
{'method': 'workspace/configuration', 'jsonrpc': '2.0', 'id': 2, 'params': {'items': [{'section': 'gopls'}]}}
```

**Comment by yegappan** [comment]
> I am not able to reproduce this problem using a test.
> 

I am able to reproduce the problem using a test now.  Basically the problem can happen when
using either a channel callback function or when using a one-time callback function.  The changes in
 9.0.1927 fixed the problem when using the channel callback function.  The above patch fixes
the problem when using the one-time callback function.

**Comment by lithammer** [comment]
> Once you confirm that this patch fixes the problem in your tests, I will open a PR upstream.

I played around with the patch and bit and so far I haven't been able to reproduce the bug. So it seems like that fixes the problem 👍 Nice!
