### ISSUE TITLE
Latest vim9script deprecated usage of # in function name

### ISSUE THREAD

**Issue by kohnish** [yegappan/lsp#40]
I suggest replace such functions with capital first letter and prepend `export`.
I'm not sure if vim8 vimrc will need to call import to call lsp#setOptions. 
It might be a good idea to migrate to global variable based config like the old times, as it is bit awkward to call import during configuration.

**Comment by kohnish** [comment]
A such commit would look like this, though probably it'll need a lot of patching to make it up to the standard of this project. 
https://github.com/kohnish/lsp/commit/74f8d32192189ec292b5a37fc6ef2adcf7e28a33

**Comment by yegappan** [comment]
Thanks for the patch. I have committed aeede042a93441f038f6b36448aaf383969bc86b to support the LSP plugin with both the latest Vim and an older version. Some of the changes are similar to what you have done in your branch. Can you try the updated plugin and let me know if you see any issues? Thanks

**Comment by kohnish** [comment]
Thanks for such a fast patch. 

This seems to work with the latest master.  (From vim9script vimrc)
```
source $HOME/.vim/pack/plugins/opt/lsp/plugin/lsp.vim
g:LspAddServer(lsp_servers)
```

**Comment by yegappan** [comment]
Instead of sourcing the plugin/lsp.vim file, why can't you use "packadd lsp"?

**Comment by kohnish** [comment]
Hey, thanks for the tip. I already do it but didn't work out (function not found) I'll try it later with up-to-date vim.
