### ISSUE TITLE
Throws errors or crashes init if LSP is not found/installed

### ISSUE THREAD

**Issue by trev-dev** [yegappan/lsp#401]
I use the Nix package manager to set up developer shells on a project by project basis, so I'm often using environment variables to define where stuff is for my editor.

Because all of my lsp servers are not "installed" globally, things like `getenv()` will return `v:null` and crash my init.  If I check for null and apply an empty string instead, I get "Error: no LSP installed for <blank>" which is likely because it's checking an empty path.

With Neovim, the lsp does not try to validate or path anything until the LSP is activated in a buffer file type.  Could this be made so for this LSP client?

My current vim9 setup:

(LSP installed at opt/LSP)

```vim
vim9script

import ('./lsp.vim') # server configs

packadd lsp
g:LspAddServer(lsp.servers)
```

**Comment by yegappan** [comment]
If the LSP server is not found when adding it, how will it be found later when it is actually used/needed?  Are you updating the PATH environment variable in a file type plugin?

If the presence of a language server executable is not validated when adding a server, then later a user may get confused if the LSP plugin functionality doesn't work.

**Comment by trev-dev** [comment]
> If the LSP server is not found when adding it, how will it be found later when it is actually used/needed? Are you updating the PATH environment variable in a file type plugin?

I'm updating it with nix and direnv :)  Nix installs the dependency and sets up the environment.  Direnv activates them when I change directories to a project.
```nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  buildInputs = with pkgs; [
    nodePackages.typescript
    nodePackages.typescript-language-server
    nodePackages.volar
  ];
  shellHook = with pkgs; ''
    export VOLAR_LSP=${nodePackages.volar}/bin/vue-language-server
    export TS_LIB=${nodePackages.typescript}/lib/node_modules/typescript/lib
  '';
}
```

> If the presence of a language server executable is not validated when adding a server, then later a user may get confused if the LSP plugin functionality doesn't work

Sure, but if I'm not intending on using a particular LSP to say, edit some markdown files, then I wouldn't want an LSP configuration to either crash my init or throw errors about the 5 different LSPs I have not currently set up on my path.  I'd care about that when I am trying to use an lsp.

**Comment by trev-dev** [comment]
As a bandaid for half my problem I wrote a type guard for my `lsp.vim` server configuration file:

```vim
vim9script
packadd lsp

def GetEnvString(varname: string): string
  var value = getenv(varname)
  return value == v:null ? varname : value
enddef

# Where an LSP server lives can vary from system to system.  Use direnv to
# configure the LSP paths.
export var servers = [
  {
    name: 'volar-server',
    filetype: ['vue', 'typescript'],
    path: GetEnvString('VOLAR_LSP'),
    args: ['--stdio'],
    initializationOptions: {
      typescript: {
        tsdk: GetEnvString('TS_LIB')
      }
    }
  }
]
```

I could contribute a way to silence the start-up warnings if it doesn't already exist:

![2023-09-24T09:53:58](https://github.com/yegappan/lsp/assets/28788713/8e49f7b9-dc93-457c-ae0a-6e8954c0322f)

**Comment by yegappan** [comment]
Can you try setting the `ignoreMissingServer` option to `true`?

**Comment by trev-dev** [comment]
Yep, that does the trick!  Thanks!
