### ISSUE TITLE
JDTLS: Code actions seem broken

### ISSUE THREAD

**Issue by trev-dev** [yegappan/lsp#403]
I can get a contextual pop up of all the available code actions at a given buffer position.  That list of options makes perfect sense.  

If I choose any of them, I get the following error:  `Error: request workspace/executeCommand failed (No delegateCommandHandler for java.apply.workspaceEdit, error = MethodNotFound)`

LSP Configuration: https://git.sr.ht/~trevdev/vim/tree/vim9lsp/item/plugins.vim#L50

**Comment by Tachi107** [comment]
Did you follow these instructions contained in section `lsp-custom-commands` of the documentation?

https://github.com/yegappan/lsp/blob/38970403dc4d602056ea4028664206ffce74e82a/doc/lsp.txt#L1675-L1698

**Comment by trev-dev** [comment]
Ah, 1700 lines deep into the help docs.  Thanks for this!  I missed it.
