### ISSUE TITLE
jdtls not working

### ISSUE THREAD

**Issue by maximyurevich** [yegappan/lsp#408]
![Screenshot from 2023-10-24 00-53-06](https://github.com/yegappan/lsp/assets/21293376/322f1ac4-c868-4471-8213-b47261c968f9)

![Screenshot from 2023-10-24 00-21-25](https://github.com/yegappan/lsp/assets/21293376/27114083-2a5a-49ea-ab05-61862d814b03)

**Comment by trev-dev** [comment]
Using version 1.26.0 I have JDTLS running well.  I see your logs indicate you're running directly from the downloads folder.  Just wondering if that was on purpose?  Is you JAVA_HOME set?
