### ISSUE TITLE
[Feature Request] Expose the Number of Errors/Info/Hints/Warnings in a given file

### ISSUE THREAD

**Issue by aGhandhii** [yegappan/lsp#409]
I am looking to add these stats to my statusline, similar to other text editors:

In VSCode:
![image](https://github.com/yegappan/lsp/assets/110639969/2be82f03-5102-4d05-b652-e036d973d9b8)

Is there currently a way to get these values without parsing the Diag list?

Thanks for the help!

**Comment by yegappan** [comment]
Yes.  The `lsp#lsp#ErrorCount()` function can be used to get the diagnostic count for the current buffer.  This function returns a Dictionary containing the "Error", "Warn", 'Hint" and "Info" count.  This is described in the help text.

**Comment by aGhandhii** [comment]
Thanks!
