### ISSUE TITLE
LspNextDiagnostic at end of diagnostics

### ISSUE THREAD

**Issue by lucas-mior** [yegappan/lsp#413]
Hello, I would like to be able to find the next diagnostic after the last 
(like when vim continues search from top of the file). Can it be done?

**Comment by yegappan** [comment]
Are you looking for the `:LspDiagNext` command?  The following commands are available to browse the diagnostics:

```
LspDiagFirst - Jump to the first diagnostic in the list
LspDiagLast - Jump to the last diagnostic in the list
LspDiagNext - Jump to the next diagnostic in the list
LspDiagNext - Jump to the previous diagnostic in the list
```

Are you looking for a command that wraps around the diagnostics, so it goes from the last diagnostic to
the first diagnostic?

**Comment by lucas-mior** [comment]
> Are you looking for a command that wraps around the diagnostics, so it goes from the last diagnostic to
the first diagnostic?
Exactly.

**Comment by nickspoons** [comment]
This is how I prefer to navigate diagnostics too, so I've made PR #482 which adds this functionality, with `:LspDiag nextWrap` and `:LspDiag prevWrap` commands.
