### ISSUE TITLE
`LspHover` popup window scroll

### ISSUE THREAD

**Issue by Song-Tianxiang** [yegappan/lsp#423]
Hello, I want to know if I can scroll the hover popup window with keybind? For now, if I want to scroll the popup window, I have to use mouse.
<img width="1088" alt="Screenshot 2023-12-13 at 2 45 17 PM" src="https://github.com/yegappan/lsp/assets/149415622/bc5e0c23-08f0-4883-9151-8710541866a8">

**Comment by yegappan** [comment]
The LSP plugin uses the Vim popup window support to display this information.  The popup window only supports scrolling using the mouse as described in https://vimhelp.org/popup.txt.html#popup-scrollbar.  So you cannot scroll the hover popup window using up/down arrow keys.  The support for this can be added though by using a popup window key filter function.

**Comment by Konfekt** [comment]
Could the popup filter parameter in `popup_create()`

https://github.com/yegappan/lsp/blob/feb71130dabe8ba23ccd0fbc18a5df3103cb2c80/autoload/lsp/codeaction.vim#L112

 then be exposed to the user similar to https://github.com/prabirshrestha/vim-lsp/pull/1058/files ?
It also would propably not hurt too much but rather help to rebind common commands such as Ctrl-F/B

**Comment by Shane-XB-Qian** [comment]
it was trying to be a simple ('KISS') UI, and normally it was not too much doc showed, 
or please try `hoverInPreview` option, make the doc show at preview.

**Comment by Konfekt** [comment]
The popup window is more convenient than the preview. Making the filter overridable will keep the UI as simple as is. It is rather counterintutiv that the scroll binds will scroll the main window when the popup window is shown, that's rarely intended

**Comment by Shane-XB-Qian** [comment]
really? :shrug: later, you maybe like to make popup can get focus, and popup can be editted, and so on. :smile:

**Comment by yegappan** [comment]
I have added the support for scrolling the hover popup window using the standard Vim keys used for scrolling.  Can you try the latest plugin out and let me know if you see any issues?

**Comment by Shane-XB-Qian** [comment]
after adding such keys, do not you feel interrupting your general operation? :sigh:

**Comment by Shane-XB-Qian** [comment]
to hover, it should be a no focus popup (if it is a popup).

**Comment by yegappan** [comment]
> after adding such keys, do not you feel interrupting your general operation? :sigh:
> to hover, it should be a no focus popup (if it is a popup).

The hover information is shown only when the `:LspHover` command is executed.
So it is acceptable to support the standard Vim scroll keys in the hover popup
window.  Note that only selected special keys are supported in the hover window.
So it shouldn't impact the handling of normal keys.

**Comment by Shane-XB-Qian** [comment]
you may press e.g  c_e  when popup is up, do not you feel it's interrupting?
hover is frequent operation, so I think it is a bad idea.
but I am not going to argue this too much, felt a little tired to argue too much.

--
shane.xb.qian

**Comment by Song-Tianxiang** [comment]
> I have added the support for scrolling the hover popup window using the standard Vim keys used for scrolling. Can you try the latest plugin out and let me know if you see any issues?

https://github.com/yegappan/lsp/pull/441

**Comment by Konfekt** [comment]
In the meanwhile, the following adaption of  https://fortime.ws/blog/2020/03/14/20200312-01/ works sufficiently well for scrolling with the arrow keys (and thus mouse wheel on Urxvt):

```vim
" Use arrow keys to scroll in popup window. Useful for the Urxvt Vtwheel
" extension that maps the mouse wheel scrolls to arrow keys (say in Mutt).

if v:version < 900
	finish
endif

function! ScrollPopup(down)
    " let winid = popup_findinfo()
    let winids = popup_list()
    if empty(winids)
        return
    else
        let winid = winids[0]
    endif

    " if the popup window is hidden, then bypass the keystrokes
    let pp = popup_getpos(winid)
    if pp.visible != 1 | return 0 | endif

    let firstline = pp.firstline + a:down
    let buf_lastline = str2nr(trim(win_execute(winid, "echo line('$')")))
    if firstline < 1
        let firstline = 1
    elseif pp.lastline + a:down > buf_lastline
        let firstline = firstline - a:down + buf_lastline - pp.lastline
    endif

    " if a scrollbar is show, then the height changes
    call popup_setoptions( winid, {'scrollbar': 0, 'firstline' : firstline } )

    return 1
endfunction

inoremap <expr> <down> ScrollPopup(3)  ? '' : '<down>'
inoremap <expr> <up>   ScrollPopup(-3) ? '' : '<up>'
nnoremap <expr> <down> ScrollPopup(3)  ? '' : '<down>'
nnoremap <expr> <up>   ScrollPopup(-3) ? '' : '<up>'
```
