### ISSUE TITLE
LspCodeAction

### ISSUE THREAD

**Issue by JetSetIlly** [yegappan/lsp#430]
The documentation says I can specify a query when invoking :LspCodeAction. However, I don't seem to be able to include actions with spaces in. I see that I should be able to specify a regular expression but nothing I come up with works.

The code action I want to specify is labelled `Organize Imports`. I've tried

- `Organize Imports`
- `Organize.Imports`
- `Organize.+Imports`
- `Organize\sImports`
etc.

I'm misunderstanding something but I'm not sure what.

I've got it working by using just `Organize` as the query but I can't be sure there won't be another code action that starts with Organize and I don't want to trigger it by accident.

**Comment by Shane-XB-Qian** [comment]
please input start with '/' ?

**Comment by JetSetIlly** [comment]
Yes. That solves it. I had tried it with an ending slash too but that's incorrect. Just a starting slash.
Thanks.
