### ISSUE TITLE
LspCodeAction unable to create files.

### ISSUE THREAD

**Issue by darkseid-is** [yegappan/lsp#445]
Getting following error when trying to create file with rust-analyzer 

```
Error: request textDocument/codeAction failed (Client does not support create capability., error = RequestFailed)
```

**Comment by yegappan** [comment]
Can you describe the list of steps (along with a sample rust file) to reproduce this issue?

**Comment by darkseid-is** [comment]
```
# create new project
cargo new hola

# open file
vim hola/src/main.rs

# add following line to top of file 
mod io;
```

`Screenshots`
neovim lsp code action
![screenshot_1706025395](https://github.com/yegappan/lsp/assets/55893621/815f0139-dc30-4ee8-9942-df98e94eadbc)

vim-lsp code action
![screenshot_1706025473](https://github.com/yegappan/lsp/assets/55893621/339362aa-7746-49b3-9c33-c0093aa25c47)

Thank you.

**Comment by yegappan** [comment]
I have committed the change https://github.com/yegappan/lsp/commit/491a32144022a0fa3ac174fea60dfb133779383e to support this.  Can you try out the latest version of the plugin?

**Comment by darkseid-is** [comment]
In the latest version, creating files works but renaming file throws an error `Error: Renaming files not supported`.

**Comment by yegappan** [comment]
Can you add the steps for renaming files using the Rust language server?

**Comment by darkseid-is** [comment]
1. In line `mod io` place cursor in `io`
2. call LspRename and enter new name

**Comment by yegappan** [comment]
Thanks for the steps.  I have committed https://github.com/yegappan/lsp/commit/72301ac00707579f7e85f91c6ba95e3a962123d5 to add support for renaming files.  Can you try using the latest version of the plugin?

**Comment by darkseid-is** [comment]
New Update works as expected.

Thank you for the quick fix and for a great tool.
