### ISSUE TITLE
LspRename fails to rename symbols across project.

### ISSUE THREAD

**Issue by darkseid-is** [yegappan/lsp#452]
![screenshot_1707391462](https://github.com/yegappan/lsp/assets/55893621/0196cd70-a9b0-4904-9ce8-3f0c7a88d182)

The above screenshot is the result of renaming a module in [alacritty](https://github.com/alacritty/alacritty).

**Comment by yegappan** [comment]
Are the files mentioned in the error messages present in those directories?  Are you using the rust language server?  Can you describe the list of steps to reproduce this issue?

**Comment by darkseid-is** [comment]
yes all the files are present. No changes were made to the repo.

steps to reproduce 
1. clone the repo.
2. open alacritty/alacritty/src/main.rs
3. change any mod * to new name.

Lsp: Rust-analyzer

**Comment by yegappan** [comment]
I have committed https://github.com/yegappan/lsp/commit/500947f69f3d9e818cd7ed7260f2541bfb353644 to address this.  Can you try the latest version of the plugin?

**Comment by darkseid-is** [comment]
New Update works as expected.

Thank you for the quick fix and for a great tool.
