### ISSUE TITLE
Semantic Highlight is lost after saving a file.

### ISSUE THREAD

**Issue by darkseid-is** [yegappan/lsp#457]
Lsp: Rust-analyzer

Steps to reproduce: Open any file and save the file couple of times

**Comment by DanielViberg** [comment]
I cant replicate, using codedark as theme. Could you provide more details on your config?

**Comment by darkseid-is** [comment]
Apparently modifying the colorscheme in vimrc causes this issued. Sorry for the wrong Bug. Thank you for your response.
