### ISSUE TITLE
Can I use CR to select a vsnip snippet?

### ISSUE THREAD

**Issue by carlotm** [yegappan/lsp#463]
Just the question in the title, not an issue.

Vsnip works great, but I have to use `<C-j>` to select a snippet for the lsp menu,
can I use just `CR` instead?

Kind Regards and thank you for this plugin!

**Comment by maximyurevich** [comment]
> Just the question in the title, not an issue.
> 
> Vsnip works great, but I have to use `<C-j>` to select a snippet for the lsp menu, can I use just `CR` instead?
> 
> Kind Regards and thank you for this plugin!

yes
