### ISSUE TITLE
Accept `<mods>` for LspGoto* commands

### ISSUE THREAD

**Issue by noscript** [yegappan/lsp#47]
Every LspGoto* command creates a window split instead of reusing the current window. Please add `<mods>` support for such commands, so the user can specify whether to use split or not.

**Comment by yegappan** [comment]
The LspGoto* commands try to open the file in the current window itself and they don't open the file in a new window.
Can you describe the steps you are using to reproduce this issue? Is the file in the current window modified?

**Comment by noscript** [comment]
> Can you describe the steps you are using to reproduce this issue? Is the file in the current window modified?

Yes, this happens only if there are unsaved modifications. I have `'hidden'` enabled.

**Comment by yegappan** [comment]
I have committed 17072e06586595da1ef6d1823b736d09cfb0a373 now to address this issue. Can you try out the latest plugin and let me know if you see any issues?

**Comment by noscript** [comment]
Thank you for the fix, it works great!
