### ISSUE TITLE
Error detected while processing function <SNR>72_AsyncRpcCb[20]

### ISSUE THREAD

**Issue by DanielViberg** [yegappan/lsp#474]
When opening https://github.com/girishji/scope.vim plugin workspace:
```
Error detected while processing function <SNR>72_AsyncRpcCb[20]..<SNR>72_ServerInitReply[37]..User Autocommands for "LspServerReady
_1"..function <SNR>26_BufferInit:
line   12:
E158: Invalid buffer name: 1
Error detected while compiling function <SNR>72_Output_cb[5]..lsp#handlers#ProcessMessages[32]..lsp#handlers#ProcessNotif[43]..<SNR
>73_ProcessDiagNotif[2]..lsp#diag#DiagNotification:
line   17:
E1028: Compiling :def function failed
```
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Mar 13 2024 08:11:41)
Included patches: 1-173

**Comment by yegappan** [comment]
Do you see this error only when opening files using the scope.vim plugin?

**Comment by DanielViberg** [comment]
I should clarify, this is without the scope.vim plugin in use. It is the behavior that results from navigating to the scope.vim workspace, in my case ~/.vim/plugged/scope.vim, and opening vim in that directory with 'vim .'
When vim has opened with netrw, the above errorr message is shown.
