### ISSUE TITLE
<c-p> does not show documentation

### ISSUE THREAD

**Issue by girishji** [yegappan/lsp#478]
Just FYI:
In the completion popup menu `<c-n>` shows lazy-doc documentation in the info popup, but if you go back by typing `<c-p>` the documentation does not show up again.

Looks like a Vim bug. I filed a report.
https://github.com/vim/vim/issues/14204

You can close this issue as appropriate.

**Comment by girishji** [comment]
Should be fixed by https://github.com/vim/vim/pull/14231

**Comment by yegappan** [comment]
Thanks.  Is this issue fixed now by your changes to Vim?

**Comment by girishji** [comment]
Yes, it is fixed.
