### ISSUE TITLE
[E149] vim error when typing lsp-options

### ISSUE THREAD

**Issue by jiax1aobo** [yegappan/lsp#484]
i installed this plugin through the guide in README

i need some details on command, but i got an error after typing `:help lsp-options`:
```
E149: Sorry, no help for lsp-options
```

maybe plugin manual was not installed correctly?

by VIM 9.0 on macOS

**Comment by yegappan** [comment]
After installing the plugin, can you run the `:helptags ALL` command in Vim?  This will generate the tags file for all the help files.
I will update the plugin documentation to reflect this.

**Comment by jiax1aobo** [comment]
yes, `:helptags ALL` command works, and it fixed my problem, now `:help lsp-options` command can work.

thanks for your working.

**Comment by jiax1aobo** [comment]
> After installing the plugin, can you run the `:helptags ALL` command in Vim? This will generate the tags file for all the help files. I will update the plugin documentation to reflect this.

yes, :helptags ALL command works, and it fixed my problem, now :help lsp-options command can work.

thanks for your working.
