### ISSUE TITLE
Perhaps should adjust the au of lsp#addFile

### ISSUE THREAD

**Issue by Shane-XB-Qian** [yegappan/lsp#5]
those lsp **server** were implemented variedly, due to some reason :-) may had to delay init lsp#addServer after vimenter,
// or whatever that may happen in user side anyhow......

if so, looks lsp would not startup IF startup vim with a fs argument.
e.g 'vim x.sh', and check by 'LspShowServers', server is Not running..

**Comment by yegappan** [comment]
Yes. Different LSP servers are implemented with different behavior. I have seen that the shell language server is different in a few aspects. For example, on startup it searches for all the shell scripts in the current directory and parses them. This delays the loading of the language server.

**Comment by Shane-XB-Qian** [comment]
yea, but this issue in this ticket looks was not due to 'deplay', but looks did not kick off lsp#startServer at all...
// i tried to fix, but so far no clue too... :-(

**Comment by Shane-XB-Qian** [comment]
it would not a problem if startup vim first, then ':e x.sh', if so, then the lsp server can be started.

**Comment by Shane-XB-Qian** [comment]
let user-self to handle if some situation needed put 'start-server' at 'vimenter' timing..
// so closing this ticket..

// but pr would still try to add a 'lsp#serverStatus' func.
