### ISSUE TITLE
Make LspInlayHints accept "toggle" in addition to "enable"/"disable"

### ISSUE THREAD

**Issue by rvighne** [yegappan/lsp#515]
I don't want to see inlay hints all the time, but it would be useful if I could quickly show and hide the hints using a single key. I can't implement this right now because you have to explicitly say "enable" or "disable" when calling LspInlayHints.

**Comment by yegappan** [comment]
Added the "toggle" option to the `:LspInlayHints` command (04b5b04312e641a3644994b332163cc5b668fb36).
