### ISSUE TITLE
:help lsp.txt doesn't work after installing

### ISSUE THREAD

**Issue by nv-quan** [yegappan/lsp#529]
The tags file is missing in doc directory. I think we should add 
`vim -u NONE -c "helptags $HOME/.vim/pack/downloads/opt/lsp/doc" -c q`
to the Installation part in README.

**Comment by KianYang-Lee** [comment]
Question: how do you usually open the help doc in vim? I would do `:help lsp` but it always point to something else. Is there anything I can do that so that the help is this package's help?

**Comment by yegappan** [comment]
The command `:help lsp` defaults to the built-in `linespace` option. To specifically target the lsp plugin tags, you can use:

* **Explicit filename**: Use `:help lsp.txt` to jump directly to the plugin's main help file.
* **Wildcard search**: Use `:help *lsp*` and press `<Tab>` to see all related tags (like `lsp-usage` or `lsp-configuration`).
* **Tab Completion**: After typing `:help lsp`, press `<Tab>` (or `Ctrl-D` to list all matches). This allows you to cycle through the options until you see the one belonging to the plugin.

**Comment by KianYang-Lee** [comment]
> The command `:help lsp` defaults to the built-in `linespace` option. To specifically target the lsp plugin tags, you can use:
> 
>     * **Explicit filename**: Use `:help lsp.txt` to jump directly to the plugin's main help file.
> 
>     * **Wildcard search**: Use `:help *lsp*` and press `<Tab>` to see all related tags (like `lsp-usage` or `lsp-configuration`).
> 
>     * **Tab Completion**: After typing `:help lsp`, press `<Tab>` (or `Ctrl-D` to list all matches). This allows you to cycle through the options until you see the one belonging to the plugin.

Thank you very much! Appreciate you taking the time to answer this 🥇
