### ISSUE TITLE
Typo in OmniSharp section of wiki

### ISSUE THREAD

**Issue by nv-quan** [yegappan/lsp#533]
As mentioned in #342, there is a typo in the instruction for OmniSharp
```
call LspAddServer([#{name: 'omnisharp',
                 \   filetype: 'cs',
                 \   path: expand('$HOME/omnisharp/omnisharp.exe'),
                 \   args: ['--z', '--languageserver', '--encoding', 'utf-8'],
                 \ }])
```
the first argument should be `-z`, otherwise the language server will not start. The issue was closed but the typo is still there.

**Comment by yegappan** [comment]
Thanks for reporting the issue.  I have updated the Wiki.
