### ISSUE TITLE
type-mismatch: request.id maybe string not num

### ISSUE THREAD

**Issue by Shane-XB-Qian** [yegappan/lsp#54]
```vim
def SendResponse(lspserver: dict<any>, request: dict<any>, result: dict<any>, error: dict<any>)
  var resp: dict<any> = lspserver.createResponse(request.id)
```

**Comment by yegappan** [comment]
Can you describe the conditions under which you ran into this problem? Which LSP server are you using?
Which request message triggered this problem?

**Comment by Shane-XB-Qian** [comment]
java, jdt from eclipse.
i do not know which request message but the err msg is type-mismatch.
and i did a debug, the request.id is string.

**Comment by Shane-XB-Qian** [comment]
i am actually not using any of lsp server in the real life/work so far, but just doing some verification or test for you or for this lsp.. :-)

**Comment by yegappan** [comment]
Thanks for taking the initiative to try the LSP plugin with different servers and your contributions.
Much appreciated.
