### ISSUE TITLE
`E684: List index out of range: 0` after :LspDocumentSymbol

### ISSUE THREAD

**Issue by jmdevin** [yegappan/lsp#555]
# Steps to Reproduce
1. Open file with vim with lsp running (used ([typescript-language-server](https://github.com/typescript-language-server/typescript-language-server)) as an example):
2. Name file `index.ts` and enter this:
```ts
function foo() {}
```
3. Do `:LspDocumentSymbol`
4. Type the letter `l` into the popup and hit `Enter`
5. See this error:
```
Error detected while processing function <SNR>60_SymbolMenuFilterKey[105]..<SNR>60_SymbolMenuItemSelected:
line   16:
E684: List index out of range: 0
```
6. Hit `Enter` and see that the `Select Symbol` popup remains
## Additional Details
I tested this on two different server types, it seems to be reproducible as long as the file has any symbols, otherwise `:LspDocumentSymbol` just doesn't appear.
Vim version: 9.1.0689

**Comment by yegappan** [comment]
Thanks for reporting the issue.  This issue is addressed by f5a27a314a07591fed23bfd5ed808a2fc2246c53.
