### ISSUE TITLE
Request ID validation

### ISSUE THREAD

**Issue by julien** [yegappan/lsp#571]
When using `zls`, an error is thrown [here](https://github.com/yegappan/lsp/blob/e34c17e7f37244ad361fb9af09fa755e21051cb3/autoload/lsp/lspserver.vim#L333). The reason is because `zls` is not sending a string that contains digits as can be seen [here](https://github.com/zigtools/zls/blob/6e0e7a89eb893650a44721c0199a88d8c17b8b61/src/Server.zig#L729) as an example.

The specification says that the request's ID can be a [number *or* a string](https://github.com/zigtools/zls/blob/6e0e7a89eb893650a44721c0199a88d8c17b8b61/src/Server.zig#L729), but, as fat as I can see it doesn't say that this ID must contain digits (but it would make sense). 

I came up with this "workaround":

```diff
diff --git a/autoload/lsp/lspserver.vim b/autoload/lsp/lspserver.vim
index 7304b00..1d4b0ed 100644
--- a/autoload/lsp/lspserver.vim
+++ b/autoload/lsp/lspserver.vim
@@ -326,11 +326,9 @@ enddef

 # send a response message to the server
 def SendResponse(lspserver: dict<any>, request: dict<any>, result: any, error: dict<any>)
-  if (request.id->type() == v:t_string
-       && (request.id->trim() =~ '[^[:digit:]]\+'
-           || request.id->trim()->empty()))
+  if (request.id->type() == v:t_string && request.id->trim()->empty())
     || (request.id->type() != v:t_string && request.id->type() != v:t_number)
-    util.ErrMsg('request.id of response to LSP server is not a correct number')
+    util.ErrMsg('request.id of response to LSP server must be a number or a string')
     return
   endif
   var resp: dict<any> = lspserver.createResponse(
```

What are your thoughts?

**Comment by yegappan** [comment]
Does this change work for you?  The Vim channel feature supports using only integers as request identifiers and doesn't currently support a string as an identifier.  But this only applies to the ch_sendexpr() and ch_evalexpr() functions.  It may not apply in this case though.  If this works for you, can you create a PR with this change?

**Comment by julien** [comment]
> Does this change work for you?

Yes it does. I've tested with zls, rust-analyzer and gopls and didn't expect any issue. 

> The Vim channel feature supports using only integers as request identifiers and doesn't currently support a string as an identifier. But this only applies to the ch_sendexpr() and ch_evalexpr() functions. 

Thanks for explaining, now I understand why we are checking for digits in the request's ID. 

I've submitted the patch in #572.

**Comment by Shane-XB-Qian** [comment]
does it really work, i am interesting this result, i remember it was me added this check to limit number only: https://github.com/yegappan/lsp/pull/55
and there is similar ticket in vim talking about the chan id type: https://github.com/vim/vim/issues/14091
so i am interesting was it really worked?

**Comment by julien** [comment]
@Shane-XB-Qian works for me with zls, i also use gopls and rust-analyzer daily and haven't had an issue since i submitted the patch. The LSP documentation mentions that the request id can be a [string or number](https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/lsp/3.18/specification.md#-request-message-).

**Comment by Shane-XB-Qian** [comment]
i do not think so: `request.id->type() == v:t_string ? request.id->str2nr() : request.id`
you made the request id always `0` if it was a string, so the 'work' perhaps was abnormal.

> The LSP documentation mentions that the request id can be a [string or number]

yes, i can be a string, but should be a number-like string, that vim ticket had said the problem.

-- 
shane.xb.qian

**Comment by julien** [comment]
> you made the request id always `0` if it was a string, so the 'work' perhaps was abnormal.

well if you have a way to fix it, feel free

> yes, i can be a string, but should be a number-like string, that vim ticket had said the problem.

sorry but "number-like-string" doesn't mean anything, but if you mean that the string has to represent a number well once again the spec doesn't say anything about that

**Comment by Shane-XB-Qian** [comment]
> > you made the request id always `0` if it was a string, so the 'work' perhaps was abnormal.
> 
> well if you have a way to fix it, feel free

i am just telling the cause, and i am the original author of that patch,
how could it be more "free"? :shrug:

> > yes, i can be a string, but should be a number-like string, that vim ticket had said the problem.
> 
> sorry but "number-like-string" doesn't mean anything, but if you mean that the string has to represent a number well once again the spec doesn't say anything about that

please read that vim ticket carefully,
1. it is a limitation in vim inside;
2. here that lsp patch was trying to make it keep be correct,
3. spec did not say must be number-like string, but reality is most lsp server is number or number-like string id.

no need to thx my help, good luck~ :smile:

-- 
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
above comment was a joke, i left a review comment at your PR #572, maybe you can re-think it in the future..
