### ISSUE TITLE
LspShowImpl alternative to LspPeekImpl

### ISSUE THREAD

**Issue by JetSetIlly** [yegappan/lsp#574]
Would it be possible for a `LspShowImpl` command be added?

There is a `LspPeekImpl` command but I prefer how the `LspShowReferences` command works as compared to the peek commands. Peek is good but showing the list in the quickfix suits my workflow better.

**Comment by JetSetIlly** [comment]
After posting the request I decided to have a closer look. It seems to be as simple as this:

`command! -nargs=0 -bar -count LspShowImpl lsp.GotoImplementation(v:false, <q-mods>, <count>)`

Is that right? Or does it need anything else?

**Comment by yegappan** [comment]
When you can have multiple locations where a symbol is referenced or defined, then using a quickfix or location list makes sense.  The LspShowImpl command will show only one location where a symbol is implemented.  So the quickfix list will have only one entry?

**Comment by JetSetIlly** [comment]
Hmm. Maybe it depends on the language the LSP is for.

I'm primarily interested in Go and so I'm using gopls. In my case, the proposed LspShowImpl command shows many locations in the quickfix.

**Comment by yegappan** [comment]
I see that we already have the "LspGotoImpl" command which provides the exact same functionality.  Can you use that command?

**Comment by JetSetIlly** [comment]
> I see that we already have the "LspGotoImpl" command which provides the exact same functionality. Can you use that command?

Ah. I didn't spot that. I was too busy looking at the Show group of commands.

LspGotoImpl is exactly what I need. Thanks.
