### ISSUE TITLE
Unknown function: LspAddServer

### ISSUE THREAD

**Issue by ForzCross** [yegappan/lsp#61]
I have a simple vimrc vim9script config for python:
```
vim9script
plug#begin()
...
Plug 'yegappan/lsp'
plug#end()
...
var lspServers = [
    {
        'filetype': ['python'],
        'path': '/usr/bin/pylsp',
        'args': []
    }
]
call LspAddServer(lspServers)
...
```
Vim version:
`VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 24 2022 18:41:57)`
`Included patches: 1-4464`

I was able to run `call LspAddServer()` after opening a *.py file, LspShowServers shows that `pylsp` was added, but is currently stopped:
```
python    not running    /usr/bin/pylsp
```
But when i try to restart it with LspServerRestart i get:
```
Error: LSP server for "test.py" is not found
```

**Comment by ForzCross** [comment]
I found out that plugin is loaded after vimrc is processed. That's why the error appeared. The following code works for adding lsp Servers:
```
g:lspServers = [
    {
        'filetype': ['python'],
        'path': '/usr/bin/pylsp',
        'args': []
    }
]
autocmd! BufReadPre * g:LspAddServer(g:lspServers)
```

**Comment by dezza** [comment]
```vim
var lspServers = [
    {
        'filetype': ['python'],
        'path': '/usr/bin/pylsp',
        'args': []
    }
]
lsp#lsp#AddServer(lspServers)
```
works

**Comment by atgote** [comment]
> ```viml
> var lspServers = [
>     {
>         'filetype': ['python'],
>         'path': '/usr/bin/pylsp',
>         'args': []
>     }
> ]
> lsp#lsp#AddServer(lspServers)
> ```
> 
> works

Yes, this works! Thanks.

**Comment by rcasta74** [comment]
In `vim9script` you should use `g:LspAddServer(lspServers)` instead of `call LspAddServer(lspServers)` otherwise it will search for a script local function.
(`call` is optional in `vim9script`)

**Comment by normen** [comment]
I don't seem to be able to get this to work with a "normal" vim8 `vimrc`..

**Comment by yegappan** [comment]
I have updated the README with the steps for registering the LSP servers and to configure the LSP options when using vim-plug to install the LSP plugin.

**Comment by normen** [comment]
> The above will directly call these functions in the autoload directory instead of the global wrapper
> functions defined in the plugin directory.  The plugin\lsp.vim file defines the global functions
> LspAddServer() and LspOptiosnSet() to add a server and to set the options respectively.
> You are not able to use these global functions in your .vimrc file?

It seems not, maybe because my vimrc isn't a vim9script?

**Comment by normen** [comment]
> I have updated the README with the steps for registering the LSP servers and to configure the LSP options when using vim-plug to install the LSP plugin.
Ah, I see, I need to use an autocommand, thanks!

**Comment by lithammer** [comment]
My solution was to call `LspAddServer` from `after/plugin/lsp.vim`. Note that I added the plugin as `start`, not `opt`.

```vim
vim9script

var config = {}
LspAddServer(config)
```

**Comment by MeralSilviusKarga** [comment]
> My solution was to call `LspAddServer` from `after/plugin/lsp.vim`. Note that I added the plugin as `start`, not `opt`.
> 
> ```viml
> vim9script
> 
> var config = {}
> g:LspAddServer(config)
> ```

So you got me thinking about sequence. My `source ~/.path/to/vim9script/secondaryconfig.vim` I put in my "legacy" .vimrc, so I could pull vim9script stuff without having to rewrite my "legacy" .vimrc to the new vim9script, I was getting errors.
I put my `source` pull of the secondary vim9script I wanted to pull from, near the end of my "legacy" vim script. After that.
No errors. 
Hope this helps someone.
