### ISSUE TITLE
Clangd error

### ISSUE THREAD

**Issue by damonmccain** [yegappan/lsp#65]
Opening vim I get this below  error, I'm using the git clone https://github.com/yegappan/lsp method to install
Error: LSP server /usr/local/bin/clangd is not found

**Comment by atgote** [comment]
> Opening vim I get this below error, I'm using the git clone https://github.com/yegappan/lsp method to install Error: LSP server /usr/local/bin/clangd is not found

Execute
`which clangd`
and recheck the path to `clangd` in your system (and whether it is installed).
For example in Slackware current (full install) the path is `/usr/bin/clangd` and not `/usr/local/bin/clangd` as shown in the instructions.

**Comment by yegappan** [comment]
To use the clangd language server, you need to install the clangd server. After installing, you need to provide
the correct path to clangd in the LSP server options.
