### ISSUE TITLE
Add ability to customize snippetSupport capability from other plugins

### ISSUE THREAD

**Issue by hrsh7th** [yegappan/lsp#72]
### Problem

I'd received the feature request for supporting `yegappan/lsp` on vim-vsnip and vim-vsnip-integ.
I'd add the support but yegappan/lsp does not provide the way to turn on `snipptSupport=true`.

### Solution

Provide the global configuration option to `snippetSupport = true`.

I think it should use in https://github.com/yegappan/lsp/blob/97da893637254590715bdd3f0726f6cd23999a8d/autoload/lsp/lspserver.vim#L97

**Comment by hrsh7th** [comment]
In the reading code a bit, the yegappan/lsp already exporse `CompletionItem` as `v:completed_item.user_data` so  I have no other changes. For example, vim-lsc integration is only to do to turned on the snippetSupport to `true`.

**Comment by yegappan** [comment]
I have committed b09afad1cd6e9396f470ab3084b9bc71efe07c33 to enable the snippet completion support.  I have tested this using the vim-vsnip plugin.  Let me know if you see any issues with this.
