### ISSUE TITLE
Omnifunc broken with autocomplete?

### ISSUE THREAD

**Issue by normen** [yegappan/lsp#73]
Hi, first of all thanks for this lightning fast vim LSP server! This is a gamechanger.

While setting up my environment I noticed that when autocomplete is enabled and I manually set the `omnifunc` to `LspOmniFunc` it won't work. Is there any way to enable autocomplete and still have the omni func?

**Comment by Shane-XB-Qian** [comment]
pls check doc for detail, there is a option for that (from my previous pr) already.
```txt
	omnicompl	(Optional) a boolean value that enables (true)
			or disables (false) omni-completion for this file
			types. By default this is set to 'v:true'.
```

**Comment by yegappan** [comment]
Do you want to use both the omni completion and the automatic completion (24x7 completion)?  Under what conditions do you want to use omni completion?  If you disable 24x7 completion by setting the 'autoComplete' LSP option to v:false, then it will enable omni completion.

**Comment by normen** [comment]
> pls check doc for detail, there is a option for that (from my previous pr) already.
> ```txt
> 	omnicompl	(Optional) a boolean value that enables (true)
> 			or disables (false) omni-completion for this file
> 			types. By default this is set to 'v:true'.
> ```

Yeah but even when enabling that manually (which it should be already) omnifunc simply breaks when calling it.

**Comment by normen** [comment]
> Do you want to use both the omni completion and the automatic completion (24x7 completion)?  Under what conditions do you want to use omni completion?  If you disable 24x7 completion by setting the 'autoComplete' LSP option to v:false, then it will enable omni completion.

I want both, auto completion and omni completion at the same time. It doesn't work. The reason is I want to be able to use the same mapping (Ctrl-Space) to open lsp and other completions.

**Comment by normen** [comment]
No, you're not getting it. I want the omni func to be `LspOmniFunc` AND I want auto completion. When I do that I get this when I call `<C-x><C-o>`

```
Fehler beim Ausführen von "function LspOmniFunc[29]..<SNR>28_Output_cb[3]..lsp#handlers#ProcessMessages[16]..lsp#handlers#ProcessReply[15]..<SNR>29_ProcessCompletionReply":
Zeile   81:
E565: Es ist nicht erlaubt Text oder Fenster zu ändern
```

**Comment by Shane-XB-Qian** [comment]
for that Yegappan had answered you,
what I said normally you had a preferred Omnifunc which was NOT from this lsp, then you can enjoy this lsp auto complete meanwhile there one yourself preferred Omnifunc.

--
shane.xb.qian

**Comment by normen** [comment]
Okay, I am sure I can _disable_ the omni function of this plugin just fine. Now for _enabling_ it while I also have autocomplete.. That one is still causing an error 🙂

**Comment by yegappan** [comment]
I have pushed 895003b09fb36ad628636b41fc5f36381306fdbe to address this issue.  Can you try this?

**Comment by normen** [comment]
> I have pushed 895003b09fb36ad628636b41fc5f36381306fdbe to address this issue.  Can you try this?

Works like a charm, thank you very much!
