### ISSUE TITLE
Use snippets in autocomplete

### ISSUE THREAD

**Issue by thechibbis** [yegappan/lsp#80]
How i can use snippets with this lsp ?

**Comment by yegappan** [comment]
Snippets are currently not supported. But I am looking into integrating the support for the snippet plugins.  Are you using any specific snippet plugin?

**Comment by Shane-XB-Qian** [comment]
here: #72 
// pls check, someone had offered a way to integrate snip already, looks that's a easy one, though i didnot try it yet.
// and lsp client perhaps better not forced to use one, for example at my local i have ultisnip yet, perhap not wish that be overlap.. :-)

**Comment by thechibbis** [comment]
> Snippets are currently not supported. But I am looking into integrating the support for the snippet plugins. Are you using any specific snippet plugin?

oh ok, im using ultisnips

**Comment by thechibbis** [comment]
> here: #72 // pls check, someone had offered a way to integrate snip already, looks that's a easy one, though i didnot try it yet. // and lsp client perhaps better not forced to set one, for example at my local i have ultisnip already, perhaps not wish that be overlap.. :-)

thx for the tips

**Comment by yegappan** [comment]
I have committed b09afad1cd6e9396f470ab3084b9bc71efe07c33 to add the support for snippet expansion.  This currently works with the vim-vsnip plugin.

**Comment by thechibbis** [comment]
> I have committed [b09afad](https://github.com/yegappan/lsp/commit/b09afad1cd6e9396f470ab3084b9bc71efe07c33) to add the support for snippet expansion. This currently works with the vim-vsnip plugin.

 i will try, thx
