### ISSUE TITLE
Autocompletion improvements

### ISSUE THREAD

**Issue by mttigg** [yegappan/lsp#87]
I have noticed odd behaviours while using autocompletion. I'm running vim `9.0.809` and I am using `tsserver` for an lsp.

1. If you type one new character on a new line the results in the completion menu will not be filtered down by the characters already typed. For example if you have `foo` and `bar` in scope and you type the letter 'f' your first result will be `bar`. Any more key presses filters down the list.
<img width="489" alt="Screen Shot 2022-10-26 at 9 35 58 PM" src="https://user-images.githubusercontent.com/26121302/198185961-f82b5e50-9ccd-48c2-8142-28c381276192.png">
<img width="481" alt="Screen Shot 2022-10-26 at 9 36 41 PM" src="https://user-images.githubusercontent.com/26121302/198185879-9de7d06c-7d9e-42c5-8e0f-9e47ed23768d.png">

2. If you have already typed `foo` and press backspace the current list in the completion menu is removed and a new list is added to the completion menu. this list is also not filtered by what you have inserted so far.
<img width="516" alt="Screen Shot 2022-10-26 at 9 36 23 PM" src="https://user-images.githubusercontent.com/26121302/198185609-b11c70bb-da98-44ea-9c40-e905731da504.png">

I have looked at how autocompletion is implemented in this plugin and noticed that it only fetches the autocompletion results when the completion menu is closed and a valid key is pressed. And I have also noticed that the completion results from the `lsp` are not filtered down, I think that vims completion menu implementation filters this list down itself.

For the first scenario I think the following is happening. Because the result from the `lsp` for autocompletion is asynchronous we have to wait for the suggested results. The problem is the vim completion menu only filters down the results on key press, so we are only given the full list from the `lsp`.

For the second scenario I'm not completely sure what is going on. We already have the results from the `lsp`, we shouldn't need to fetch those results a second time but we do. This isn't the usual behaviour of the completion menu, usually on backspace the completion menu stays visible. I could see fetching on backspace covering some edge cases though.

**Comment by andlrc** [comment]
Maybe this PR #120 is related?

**Comment by mttigg** [comment]
@andlrc I think you are right. This is the same behaviour being observed with autocompletion being enabled or disabled.

**Comment by techntools** [comment]
I am facing the same issue as well

![image](https://user-images.githubusercontent.com/71767293/224552505-f26d39e4-c306-42e5-84b9-2794da82f775.png)

**Comment by andlrc** [comment]
@techntools can you update and see if the problem is fixed?

**Comment by techntools** [comment]
Yes. Its fixed.

![image](https://user-images.githubusercontent.com/71767293/225194218-536d30b4-f5eb-4303-83fd-45a830523795.png)
