### ISSUE TITLE
AutoCmd for LSP status updates?

### ISSUE THREAD

**Issue by normen** [yegappan/lsp#88]
Hey,

to display the error count in my lightline status line I am using `lsp#lsp#ErrorCount` which basically works but the status line isn't updated when the LSP detects new errors. I have to do some action like `LspOutline` to update the status line.

The `vim-lsp` plugin solves this by having an `autocmd` called `lsp_diagnostics_updated` which is executed when the LSP changes so I can update the status line like shown below. Maybe something like that could be added to this plugin.

```
autocmd User lsp_diagnostics_updated call lightline#update()
```

Cheers!

**Comment by yegappan** [comment]
I have committed 23efc7394975eb2a0a1d74a7b58d230876889893 now to add the LspDiagsUpdated autocmd.

**Comment by normen** [comment]
Booom 🙂 Thanks!
