### ISSUE TITLE
Error with LSP on empty line

### ISSUE THREAD

**Issue by normen** [yegappan/lsp#91]
I am getting this error here in combination with the `vim-language-server` when I execute the omni complete mapping without any preceding characters, seems like it tries to send some empty variables to the LSP.

```
Error(LSP): request textDocument/completion failed (Request textDocument/completi... arguments[[object Object], [object Object], undefined, undefined], code = -32603)
```

**Comment by yegappan** [comment]
This looks like a bug in the vim-language-server.  You should open a issue with the vim-language-server.  The error code "32603" refers to an internal error.  I am also able to reproduce the same error with the vim-lsp language server.
