### ISSUE TITLE
code action via workspace/executeCommand

### ISSUE THREAD

**Issue by Shane-XB-Qian** [yegappan/lsp#95]
`Error(LSP): request workspace/executeCommand failed (No delegateCommandHandler for java.apply.workspaceEdit, code = -32601)`

code action not impl yet, for now just a list of code action hint.

**Comment by yegappan** [comment]
Which Java language server are you using?  Can you describe the steps to reproduce this issue?

**Comment by Shane-XB-Qian** [comment]
jdt for java from eclipse.
1, write a simple java class with one unused `import`
2, then issue `LspCodeAction`, chose `remove used import` then.
3, err like above.

**Comment by yegappan** [comment]
I have added support for using customer code-action command handlers in a575feb8d48d461b463b6604e842711c392c0d62.  I have tested it with the Java language server.  I tested some of the refactoring items listed in https://code.visualstudio.com/docs/java/java-refactoring.  Can you try it out (with the custom handler described in the help) and let me know if you see any issues?

**Comment by yegappan** [comment]
I have added support for using customer code-action command handlers in a575feb8d48d461b463b6604e842711c392c0d62.  I have tested it with the Java language server.  I tested some of the refactoring items listed in https://code.visualstudio.com/docs/java/java-refactoring.  Can you try it out (with the custom handler described in the help) and let me know if you see any issues?

**Comment by Shane-XB-Qian** [comment]
thx. that's worked, very nice.

// i've opened #96 to correct the doc a bit, though.
